// Where results land: proposals/<UTC>.jsonl (one measured proposal per line) and INDEX.md, a ranked view of every
// proposal ever written, regenerated from the JSONL files so it can never drift from them.
import { appendFileSync, existsSync, readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { LOG_ROOT, ensureDir } from './common.mjs';

export const proposalsDir = (logRoot = LOG_ROOT) => ensureDir(join(logRoot, 'proposals'));

export function appendRecords(file, records) {
  if (records.length) appendFileSync(file, records.map(r => JSON.stringify(r)).join('\n') + '\n');
}

/** Latest measurement per proposal id across every JSONL file. */
export function readAllRecords(logRoot = LOG_ROOT) {
  const dir = join(logRoot, 'proposals');
  if (!existsSync(dir)) return [];
  const latest = new Map();
  for (const file of readdirSync(dir).filter(f => f.endsWith('.jsonl')).sort()) {
    for (const line of readFileSync(join(dir, file), 'utf8').split('\n')) {
      if (!line.trim()) continue;
      let row;
      try { row = JSON.parse(line); } catch { continue; }
      if (!row?.id || !row.coverage) continue;
      const prior = latest.get(row.id);
      if (!prior || String(row.measured_at) >= String(prior.measured_at)) latest.set(row.id, { ...row, _file: file });
    }
  }
  return [...latest.values()];
}

const cell = (s, max = 110) => {
  const flat = String(s ?? '').replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();
  return flat.length > max ? `${flat.slice(0, max - 3)}...` : flat;
};
const pct = x => `${(100 * x).toFixed(0)}%`;

export function renderIndex(records) {
  const sorted = [...records].sort((a, b) =>
    b.coverage.coverage - a.coverage.coverage
    || b.coverage.coverage_with_partial - a.coverage.coverage_with_partial
    || String(a.name).localeCompare(String(b.name)));
  const lastRun = sorted.map(r => r.run).sort().pop() ?? 'none';
  const lines = [
    '# Stack proposals from the local generator',
    '',
    'Regenerated by scripts/stacks from proposals/*.jsonl. Sorted by coverage, then by coverage counting partials.',
    'Coverage = needs present in the live data model / needs. Partial (related structure exists, not the thing itself)',
    'is shown beside it and is not counted as coverage. Every row is a proposal, not a decision; status starts at proposed.',
    '',
    `Proposals: ${sorted.length}. Latest run: ${lastRun}.`,
    '',
    '| # | Name | Coverage | Present / partial / missing | Proposed | Status | Question | File |',
    '|---|---|---|---|---|---|---|---|',
    ...sorted.map((r, i) => `| ${i + 1} | ${cell(r.name, 70)} | ${pct(r.coverage.coverage)} | ${r.coverage.present} / ${r.coverage.partial} / ${r.coverage.missing} | ${String(r.proposed_at ?? '').slice(0, 10)} | ${r.status ?? 'proposed'} | ${cell(r.proposal?.question)} | ${r._file} |`),
    '',
  ];
  return lines.join('\n');
}

export function writeIndex(logRoot = LOG_ROOT) {
  const records = readAllRecords(logRoot);
  const path = join(ensureDir(logRoot), 'INDEX.md');
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, renderIndex(records));
  renameSync(tmp, path);
  return { path, count: records.length };
}
