version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for npm packages in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Group all updates into a single PR
    groups:
      dependencies:
        patterns:
          - "*"
    # Set reviewers for PRs
    reviewers:
      - "sss97133"
    # Limit to 5 open PRs at a time
    open-pull-requests-limit: 5
    # Allow up to 10 dependencies to update in each PR
    pull-request-branch-name:
      separator: "-"
    # Specify labels for PRs
    labels:
      - "dependencies"
      - "npm"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflow files in the .github/workflows directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Group all GitHub Actions updates into a single PR
    groups:
      actions:
        patterns:
          - "*"
    # Set reviewers for PRs
    reviewers:
      - "sss97133"
    # Limit to 2 open PRs at a time
    open-pull-requests-limit: 2
    # Specify labels for PRs
    labels:
      - "dependencies"
      - "github-actions"
