version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "54322:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      # Enable postgres extension creation
      POSTGRES_INITDB_ARGS: "--data-checksums"

volumes:
  postgres-data:
