version: '3.8'

services:
  # Development environment with hot-reloading
  app-dev:
    image: node:20-alpine
    container_name: nuke-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173" # Vite dev server
      - "54321:54321" # Supabase local development
    environment:
      - NODE_ENV=development
      - VITE_APP_NAME=Nuke
      - VITE_APP_DESCRIPTION="Vehicle Management Platform"
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Production build environment
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuke-prod
    ports:
      - "8080:8080" # Nginx serves on port 8080 inside container
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  node_modules:
