version: '3.8'

services:
  # Development environment with hot-reloading
  app-dev:
    image: node:18-alpine
    container_name: nuke-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173" # Vite dev server
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  # Production build environment
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuke-prod
    ports:
      - "8080:80" # Nginx serves on port 80 inside container
    environment:
      - NODE_ENV=production
    # Only uncomment if you need to customize the production environment
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  node_modules:
