#!/bin/bash
SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrZ2F5YnZyZXJuc3RwbHpqYWFtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczODM2OTAyMSwiZXhwIjoyMDUzOTQ1MDIxfQ.NEbqSnSamR5f7Fqon25ierv5yJgdDy_o2nrixOej_Xg"

# Execute SQL directly
psql "postgresql://postgres.qkgaybvrernstplzjaam@db.qkgaybvrernstplzjaam.supabase.co:5432/postgres" \
  -f DEPLOY_PROFESSIONAL_FINANCIAL_SYSTEM.sql
