// BuildPlanStatusBar.tsx — surfaces the on-disk build plan state above the
// existing compute-generated status bar. Fetches `/build-plan-status.json`
// (regenerated by scripts/build-plan-status.py). Clickable blockers and
// receipts expand a drawer with per-item detail.

import { useEffect, useMemo, useState } from 'react';

type Blocker = { id: string; title: string; class: string; owner: string };
type Receipt = { id: string; status: string };
type Subharness = { slug: string; wires: number; connectors: number; bom_lines: number; bom_total: number };
type Status = {
  generated_at: string;
  totals: {
    wires: number; connectors: number; bom_line_items: number;
    bom_total_dollars: number; labor_hours: number; labor_cost_dollars: number; grand_total_dollars: number;
  };
  subharnesses: Subharness[];
  blockers: Blocker[];
  blocker_count: number;
  receipts: Receipt[];
  receipt_count: number;
  ibooster_variant: string;
  fab_readiness_pct: number;
};

interface Props {
  /** React node rendered at the far left of the bar (e.g., tab buttons). */
  leadingContent?: React.ReactNode;
  /** React node rendered between FAB % and UPDATED on the right side. */
  trailingContent?: React.ReactNode;
}

export function BuildPlanStatusBar({ leadingContent, trailingContent }: Props = {}) {
  const [status, setStatus] = useState<Status | null>(null);
  const [drawer, setDrawer] = useState<'none' | 'blockers' | 'receipts' | 'subs' | 'downloads'>('none');

  useEffect(() => {
    fetch('/build-plan-status.json')
      .then(r => (r.ok ? r.json() : null))
      .then(setStatus)
      .catch(() => setStatus(null));
  }, []);

  const ago = useMemo(() => {
    if (!status?.generated_at) return '';
    const diff = Math.round((Date.now() - new Date(status.generated_at).getTime()) / 1000);
    if (diff < 60) return `${diff}s ago`;
    if (diff < 3600) return `${Math.round(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.round(diff / 3600)}h ago`;
    return `${Math.round(diff / 86400)}d ago`;
  }, [status?.generated_at]);

  if (!status) {
    return (
      <div style={bar(false)}>
        {leadingContent}
        <span style={labelStyle}>BUILD PLAN</span>
        <span style={valStyle}>NOT GENERATED — run `python3 scripts/build-plan-status.py`</span>
        {trailingContent && <div style={{ marginLeft: 'auto' }}>{trailingContent}</div>}
      </div>
    );
  }

  const t = status.totals;
  return (
    <>
      <div style={bar(true)}>
        {leadingContent}
        <span style={labelStyle}>BUILD PLAN</span>
        <span style={valStyle}>{t.wires}W</span>
        <span style={labelStyle}>CONN</span>
        <span style={valStyle}>{t.connectors}</span>
        <span style={labelStyle}>GRAND</span>
        <span style={valStyle}>${t.grand_total_dollars.toLocaleString()}</span>

        <button style={btn(status.blocker_count > 0 ? 'warn' : 'ok')} onClick={() => setDrawer(drawer === 'blockers' ? 'none' : 'blockers')}>
          {status.blocker_count} BLK
        </button>
        <button style={btn('info')} onClick={() => setDrawer(drawer === 'receipts' ? 'none' : 'receipts')}>
          {status.receipt_count} RCP
        </button>
        <button style={btn('info')} onClick={() => setDrawer(drawer === 'subs' ? 'none' : 'subs')}>
          6 SUB
        </button>
        <button style={btn('ok')} onClick={() => setDrawer(drawer === 'downloads' ? 'none' : 'downloads')}>
          ⇩ SHOP PACKET
        </button>

        <div style={{ marginLeft: 'auto', display: 'flex', gap: 6, alignItems: 'center' }}>
          {trailingContent}
          <span style={{ ...labelStyle, marginLeft: 8 }}>FAB</span>
          <span style={{ ...valStyle, color: status.fab_readiness_pct >= 95 ? '#22c55e' : '#eab308' }}>
            {status.fab_readiness_pct}%
          </span>
          <span style={{ ...valStyle, color: '#555', marginLeft: 4, marginRight: 0 }}>· {ago}</span>
        </div>
      </div>

      {drawer === 'blockers' && (
        <div style={drawerStyle}>
          <div style={drawerTitle}>REAL BLOCKERS — {status.blocker_count} ITEMS</div>
          {status.blockers.length === 0 ? (
            <div style={emptyStyle}>No real blockers. Fab-ready.</div>
          ) : (
            status.blockers.map(b => (
              <div key={b.id} style={drawerRow}>
                <span style={pillStyle(b.class)}>{b.id}</span>
                <span style={drawerRowTitle}>{b.title}</span>
                <span style={drawerRowMeta}>{b.class} · {b.owner}</span>
              </div>
            ))
          )}
          <div style={drawerFooter}>
            Close by clicking BLOCKERS again. Source: docs/wiring/build-plan/CONFIDENCE_AUDIT.md
          </div>
        </div>
      )}

      {drawer === 'receipts' && (
        <div style={drawerStyle}>
          <div style={drawerTitle}>WIRING RECEIPTS — {status.receipt_count} FILED</div>
          {status.receipts.length === 0 ? (
            <div style={emptyStyle}>No receipts filed yet.</div>
          ) : (
            status.receipts.map(r => (
              <div key={r.id} style={drawerRow}>
                <span style={pillStyle(r.status)}>{r.status}</span>
                <span style={drawerRowTitle}>{r.id}</span>
              </div>
            ))
          )}
          <div style={drawerFooter}>
            Source: docs/wiring/receipts/
          </div>
        </div>
      )}

      {drawer === 'subs' && (
        <div style={drawerStyle}>
          <div style={drawerTitle}>SUBHARNESSES — per-scope totals</div>
          {status.subharnesses.map(s => (
            <div key={s.slug} style={drawerRow}>
              <span style={drawerRowTitle}>{s.slug}</span>
              <span style={drawerRowMeta}>{s.wires} wires · {s.connectors} conn · ${s.bom_total.toLocaleString()}</span>
            </div>
          ))}
          <div style={drawerFooter}>
            iBooster variant: {status.ibooster_variant}
          </div>
        </div>
      )}

      {drawer === 'downloads' && (
        <div style={drawerStyle}>
          <div style={drawerTitle}>SHOP PACKET — ship-ready files</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 6 }}>
            {SHOP_PACKET_FILES.map(f => (
              <a key={f.path} href={f.path} download
                 style={downloadLinkStyle}
                 onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.background = '#1e293b'; }}
                 onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.background = 'transparent'; }}>
                <span style={downloadBadge(f.kind)}>{f.kind}</span>
                <span style={downloadName}>{f.name}</span>
                <span style={downloadHint}>{f.hint}</span>
              </a>
            ))}
          </div>
          <div style={drawerFooter}>
            Files regenerate automatically when anything in docs/wiring/build-plan/ or docs/wiring/receipts/ changes (launchd WatchPaths → build-plan-status loop).
          </div>
        </div>
      )}
    </>
  );
}

const SHOP_PACKET_FILES: Array<{ path: string; name: string; kind: 'CSV' | 'MD'; hint: string }> = [
  { path: '/build-plan/BUILD_PLAN.md',              name: 'BUILD_PLAN.md',              kind: 'MD',  hint: 'cover document — send this first' },
  { path: '/build-plan/MASTER_CUT_LIST.csv',        name: 'MASTER_CUT_LIST.csv',        kind: 'CSV', hint: '332 wires — every cut the shop makes' },
  { path: '/build-plan/MASTER_CONNECTOR_SCHEDULE.csv', name: 'MASTER_CONNECTOR_SCHEDULE.csv', kind: 'CSV', hint: '174 connectors with vendor SKUs' },
  { path: '/build-plan/MASTER_BOM.csv',             name: 'MASTER_BOM.csv',             kind: 'CSV', hint: '366 line items, $12,728 deduped' },
  { path: '/build-plan/MASTER_ASSEMBLY_SEQUENCE.md', name: 'MASTER_ASSEMBLY_SEQUENCE.md', kind: 'MD', hint: 'phase-by-phase build order' },
  { path: '/build-plan/MASTER_TEST_PROCEDURE.md',   name: 'MASTER_TEST_PROCEDURE.md',   kind: 'MD',  hint: 'system-level integration tests' },
  { path: '/build-plan/BLOCKING_UNKNOWNS.md',       name: 'BLOCKING_UNKNOWNS.md',       kind: 'MD',  hint: 'original 43 items (archive)' },
  { path: '/build-plan/CONFIDENCE_AUDIT.md',        name: 'CONFIDENCE_AUDIT.md',        kind: 'MD',  hint: 'reclassified: 7 real blockers' },
  { path: '/build-plan/RISK_ATLAS.md',              name: 'RISK_ATLAS.md',              kind: 'MD',  hint: 'per-segment confidence + over-cut margins' },
];

const downloadLinkStyle: React.CSSProperties = {
  display: 'grid', gridTemplateColumns: '40px 1fr', gap: 6,
  padding: '4px 8px',
  background: 'transparent',
  color: '#e2e8f0',
  textDecoration: 'none',
  border: '1px solid #334',
  fontFamily: 'Arial', fontSize: '9px',
  alignItems: 'center',
  cursor: 'pointer',
};

const downloadBadge = (kind: 'CSV' | 'MD'): React.CSSProperties => ({
  padding: '1px 4px',
  background: kind === 'CSV' ? '#14532d' : '#1e3a8a',
  color: kind === 'CSV' ? '#dcfce7' : '#dbeafe',
  fontFamily: 'Arial', fontSize: '8px', fontWeight: 700,
  textAlign: 'center' as const,
  gridRow: '1 / span 2',
  alignSelf: 'center',
});

const downloadName: React.CSSProperties = {
  color: '#e2e8f0', fontFamily: 'Courier New', fontSize: '10px',
};

const downloadHint: React.CSSProperties = {
  color: '#64748b', fontSize: '8px',
};

// ── styles (respect frontend rules: Arial, Courier New for mono, no radius, 2px borders) ─

const bar = (loaded: boolean): React.CSSProperties => ({
  display: 'flex', alignItems: 'center', gap: 4,
  padding: '0 12px', height: 26,
  background: loaded ? '#0f172a' : '#3a1414',
  borderBottom: '1px solid #334',
  fontFamily: 'Arial', fontSize: '8px', fontWeight: 700, letterSpacing: '0.5px',
  flexShrink: 0,
});

const labelStyle: React.CSSProperties = {
  color: '#64748b', textTransform: 'uppercase',
};

const valStyle: React.CSSProperties = {
  color: '#e2e8f0', fontFamily: 'Courier New', fontSize: '10px', marginRight: 8,
};

const btn = (tone: 'ok' | 'warn' | 'info'): React.CSSProperties => ({
  padding: '2px 8px', marginRight: 4,
  background: 'transparent',
  color: tone === 'warn' ? '#eab308' : tone === 'ok' ? '#22c55e' : '#60a5fa',
  border: '2px solid ' + (tone === 'warn' ? '#eab308' : tone === 'ok' ? '#22c55e' : '#60a5fa'),
  cursor: 'pointer',
  fontFamily: 'Arial', fontSize: '8px', fontWeight: 700,
  textTransform: 'uppercase', letterSpacing: '0.5px',
});

const drawerStyle: React.CSSProperties = {
  background: '#0f172a',
  borderBottom: '2px solid #334',
  padding: '6px 12px 10px',
  maxHeight: 280, overflow: 'auto',
  fontFamily: 'Arial', fontSize: '10px',
  color: '#e2e8f0',
};

const drawerTitle: React.CSSProperties = {
  fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px',
  color: '#94a3b8', fontSize: '9px', marginBottom: 6, paddingBottom: 4,
  borderBottom: '1px solid #334',
};

const drawerRow: React.CSSProperties = {
  display: 'grid',
  gridTemplateColumns: '80px 1fr auto',
  gap: 8, alignItems: 'center',
  padding: '3px 0',
  borderBottom: '1px solid #1e293b',
};

const drawerRowTitle: React.CSSProperties = {
  color: '#e2e8f0', fontFamily: 'Courier New', fontSize: '10px',
};

const drawerRowMeta: React.CSSProperties = {
  color: '#64748b', fontFamily: 'Courier New', fontSize: '9px',
};

const emptyStyle: React.CSSProperties = {
  color: '#64748b', fontStyle: 'italic', padding: '8px 0',
};

const drawerFooter: React.CSSProperties = {
  color: '#475569', fontSize: '8px', marginTop: 8, textAlign: 'right',
};

const pillStyle = (cls: string): React.CSSProperties => {
  const map: Record<string, { bg: string; fg: string }> = {
    'Skylar-decision': { bg: '#1e40af', fg: '#dbeafe' },
    'Safety-critical physical': { bg: '#7f1d1d', fg: '#fecaca' },
    'Safety-critical sourcing': { bg: '#7f1d1d', fg: '#fecaca' },
    'draft': { bg: '#713f12', fg: '#fef3c7' },
    'validated': { bg: '#14532d', fg: '#dcfce7' },
  };
  const c = map[cls] || { bg: '#334155', fg: '#e2e8f0' };
  return {
    padding: '2px 6px', background: c.bg, color: c.fg,
    fontFamily: 'Arial', fontSize: '8px', fontWeight: 700,
    textTransform: 'uppercase', letterSpacing: '0.5px',
    textAlign: 'center' as const,
  };
};
