#!/usr/bin/env python3
"""Audit index of the K5 part models: every part script in this folder -> catalog/part_models.yaml (for review)
and nuke_frontend/public/wiring/part-models/index.json (for the layout page and the site).

A part script is a file here named by its endpoint id (the mounts.yaml `ends:` id, e.g. M130-A.py) that defines
build() -> (bodies, keepouts, extra) and part_meta(bodies) -> dict. This builds each part (a second or two each) so
the index carries the part's own measured checks, then lints the records.

    ~/k5-harness-pull/parts/.venv/bin/python docs/wiring/calc-data/cad/fab/index_v5.py

The lint fails on: a dimension without a source, a basis outside maker/scaled/design/assumed, a colour without its
source, an endpoint that isn't in mounts.yaml `ends:`, a failed check, or a run of 32+ hex characters.
"""
import importlib.util
import json
import re
import sys
from datetime import date
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CALC = HERE.parents[1]
REPO = CALC.parents[2]
MOUNTS = CALC / "catalog" / "mounts.yaml"
OUT_YAML = CALC / "catalog" / "part_models.yaml"
OUT_JSON = REPO / "nuke_frontend" / "public" / "wiring" / "part-models" / "index.json"
BASES = {"maker", "scaled", "design", "assumed"}
SHAPE_BASES = {"maker drawing", "datasheet dims", "scaled from photo", "twin object", "not sourced"}
HEADER = """# K5 harness — PART MODELS: every physical piece the harness plugs into, as true-size parametric CAD
# (generated by cad/fab/index_v5.py from the part scripts in cad/fab/; do not edit by hand)
#
# Owner, 2026-09-29: "need the product footprints ... things need to be to size and color", then "the fabricator
# obviously needs instructions on how the parts will be made". One record per part script (cad/fab/<id>.py, build123d).
# Each script writes <id>.step, <id>.glb, <id>_drawing.svg and <id>.params.json to a local folder; none of those
# files are committed. Check any part one at a time: every dimension below carries its source and basis, and
# `checks` are the part's own solids measured against the maker's printed numbers at build time.
#
#   shape_basis  maker drawing | datasheet dims | scaled from photo | twin object | not sourced
#   params       dimension: value (mm or degrees), source (doc + page, or URL + date), basis:
#                  maker = printed by the maker; scaled = measured off the maker's drawing at its printed scale;
#                  design = our clearance or choice; assumed = in no source (say so, don't hide it)
#   frame        the part's own axes. Origin at the mounting-face centre; +Z out of the mounting face.
#   axes         the same, for code: mount_normal (always +Z), maker_up (the axis that is up in the maker's view),
#                faces (which way the plugs, label and mounting face point). World rotation is the placement's call.
#   attach       where each wire lands: {n, ep (endpoint id), at [mm], dir (the way the wire leaves)}
#   mount        mounting holes and studs: {n, at, dir (the way the bolt goes in), d}
"""


def load_parts():
    ends = {e["id"] for e in yaml.safe_load(open(MOUNTS))["ends"]}
    parts = []
    sys.path.insert(0, str(HERE))
    for f in sorted(HERE.glob("*.py")):
        if f.stem not in ends:
            continue
        spec = importlib.util.spec_from_file_location(f"part_{f.stem.replace('-', '_')}", f)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        built = mod.build()
        meta = mod.part_meta(built[0])
        meta["script"] = str(f.relative_to(REPO))
        parts.append(meta)
    return parts, ends


def lint(parts, ends):
    errors = []
    for p in parts:
        pid = p.get("id", "?")
        for k in ("what", "maker", "maker_pn", "shape_basis", "dims_mm", "frame", "axes", "colors", "attach", "params"):
            if not p.get(k):
                errors.append(f"{pid}: missing {k}")
        if p.get("shape_basis") not in SHAPE_BASES:
            errors.append(f"{pid}: shape_basis {p.get('shape_basis')!r}")
        for ep in p.get("endpoints", [pid]):
            if ep not in ends:
                errors.append(f"{pid}: endpoint {ep} not in mounts.yaml ends")
        for d in p.get("params", []):
            if not d.get("source"):
                errors.append(f"{pid}.{d.get('name')}: no source")
            if d.get("basis") not in BASES:
                errors.append(f"{pid}.{d.get('name')}: basis {d.get('basis')!r}")
        for cn, c in (p.get("colors") or {}).items():
            if not re.fullmatch(r"#[0-9a-f]{6}", c.get("hex", "")) or not c.get("from"):
                errors.append(f"{pid}: colour {cn} needs hex + from")
        for c in p.get("checks", []):
            if not c.get("ok"):
                errors.append(f"{pid}: check failed: {c.get('check')} (model {c.get('model')}, drawing {c.get('drawing')})")
        for a in p.get("attach", []):
            if a.get("ep") not in p.get("endpoints", [pid]):
                errors.append(f"{pid}: attach {a.get('n')} names endpoint {a.get('ep')} not on this part")
    return errors


def main():
    parts, ends = load_parts()
    errors = lint(parts, ends)
    doc = {"generated": str(date.today()), "parts": parts}
    text = HEADER + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=120)
    m = re.search(r"[0-9a-fA-F]{32,}", text)
    if m:
        errors.append(f"a run of {len(m.group())} hex characters (secret scanner)")
    counts = {}
    for p in parts:
        counts[p["shape_basis"]] = counts.get(p["shape_basis"], 0) + 1
    print(f"{len(parts)} part(s): " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())))
    if errors:
        print("\n".join("LINT " + e for e in errors))
        sys.exit(1)
    OUT_YAML.write_text(text)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    slim = {"generated": doc["generated"], "source": "docs/wiring/calc-data/catalog/part_models.yaml",
            "parts": {p["id"]: {k: p[k] for k in ("endpoints", "what", "maker", "maker_pn", "shape_basis", "dims_mm", "frame",
                                                  "axes", "colors", "attach", "mount", "keepout") if k in p} for p in parts}}
    OUT_JSON.write_text(json.dumps(slim, indent=1, ensure_ascii=False) + "\n")
    print("wrote", OUT_YAML.relative_to(REPO), "and", OUT_JSON.relative_to(REPO))


if __name__ == "__main__":
    main()
