\set ON_ERROR_STOP on
SELECT fixture_reject($a$UPDATE derivation_queue SET cost_cents=NULL WHERE evidence_type='listing_page_snapshot' AND status='pending'$a$,'NULL deterministic cost refused');
SELECT fixture_reject($a$UPDATE derivation_queue SET cost_cents=1 WHERE evidence_type='listing_page_snapshot' AND status='pending'$a$,'paid cost refused');
SELECT fixture_reject($a$UPDATE derivation_queue SET credential_source=NULL WHERE evidence_type='listing_page_snapshot' AND status='pending'$a$,'NULL credential route refused');
SELECT fixture_reject($a$UPDATE derivation_queue SET extractor_slug='fixture-private-reader' WHERE evidence_type='listing_page_snapshot' AND status='pending'$a$,'private extractor cannot steal source route');
SELECT fixture_reject($a$UPDATE derivation_queue SET user_id=gen_random_uuid() WHERE evidence_type='listing_page_snapshot' AND status='pending'$a$,'private payer cannot be bound to source route');
SELECT fixture_reject($a$UPDATE derivation_queue SET source_snapshot_id=NULL WHERE evidence_type='listing_page_snapshot' AND status='pending'$a$,'NULL typed capture refused');
SELECT fixture_reject($a$UPDATE derivation_queue SET source_vehicle_id=md5('fixture-vehicle-1')::uuid WHERE evidence_type='listing_page_snapshot' AND status='pending'$a$,'immutable parent cannot rebind');
SELECT fixture_reject($a$UPDATE derivation_queue SET evidence_type='auction_comment',source_snapshot_id=NULL,source_vehicle_id=NULL WHERE evidence_type='listing_page_snapshot' AND status='pending'$a$,'capture work cannot change lane');
SELECT fixture_reject($a$UPDATE derivation_queue SET source_vehicle_id=md5('fixture-vehicle-1')::uuid WHERE evidence_type='auction_comment'$a$,'legacy lane cannot acquire capture keys');
SELECT fixture_reject($a$UPDATE derivation_queue SET observation_ids=ARRAY[gen_random_uuid()] WHERE evidence_id=md5('fixture-capture-1')::uuid$a$,'completed typed result cannot disagree with array');
SELECT fixture_reject($a$SELECT claim_bat_sale_snapshots(NULL,20)$a$,'NULL worker refused');
SELECT fixture_reject($a$SELECT claim_bat_sale_snapshots('x',NULL)$a$,'NULL batch refused');
SELECT fixture_reject($a$SELECT claim_bat_sale_snapshots('x',21)$a$,'overwide batch refused');
SELECT fixture_reject($a$SELECT finish_bat_sale_snapshot(gen_random_uuid(),'x','skipped',NULL,'private raw error body')$a$,'unbounded private error text refused');
SELECT fixture_reject($a$SELECT finish_bat_sale_snapshot(gen_random_uuid(),'x','skipped',gen_random_uuid(),'unknown')$a$,'refusal cannot pretend to be an observation');
SET ROLE anon;
SELECT fixture_reject($a$SELECT claim_bat_sale_snapshots('x',1)$a$,'actual anonymous RPC execution denied','42501');
RESET ROLE;
SET ROLE authenticated;
SELECT fixture_reject($a$SELECT finish_bat_sale_snapshot(gen_random_uuid(),'x','skipped',NULL,'unknown')$a$,'actual signed-in completion execution denied','42501');
RESET ROLE;
SELECT fixture_capture(95,'{"metadata":{"vehicle_id":"garbage"}}');
SELECT fixture_capture(96,'{"listing_kind":"non_vehicle_item"}');
SELECT fixture_capture(97,'{"metadata":{"parsed_at":null}}');
SELECT fixture_assert((SELECT count(*)=0 FROM derivation_queue WHERE evidence_id IN(md5('fixture-capture-95')::uuid,md5('fixture-capture-96')::uuid,md5('fixture-capture-97')::uuid)),'invalid identity nonvehicle and clock headers not queued');
-- Finite cursor and pending gate:500header keys,1..20claim bounds, EOF distinct.
SELECT fixture_capture(n,'{"metadata":{"vehicle_matched":false}}') FROM generate_series(200,701)n;
UPDATE bat_sale_replay_state SET snapshot_cursor=NULL,scan_completed_at=NULL,keys_seen=0,seed_queued=0;
SELECT seed_bat_sale_snapshots();
SELECT fixture_assert((SELECT keys_seen=500 AND scan_completed_at IS NULL FROM bat_sale_replay_state),'full500header page does not falsely claim exhaustion');
SELECT seed_bat_sale_snapshots();
SELECT fixture_assert((SELECT keys_seen=511 AND scan_completed_at IS NOT NULL FROM bat_sale_replay_state),'next short page records true fixture EOF');
SELECT fixture_capture(n) FROM generate_series(1000,1501)n;
SELECT fixture_assert((SELECT count(*)=0 FROM claim_derivation_work('legacy',1000,NULL)),'legacy dispatcher excludes all new work');
UPDATE bat_sale_replay_state SET snapshot_cursor=NULL,scan_completed_at=NULL,last_seed_at=NULL;
SELECT fixture_assert(seed_bat_sale_snapshots()=0 AND(SELECT last_seed_at IS NULL FROM bat_sale_replay_state),'pending500seed gate does not forge progress');
SELECT fixture_assert((SELECT count(*)=20 FROM claim_bat_sale_snapshots('bounded',20)),'source claims bounded20');
SELECT fixture_assert((SELECT count(*)=20 FROM derivation_queue WHERE status='claimed' AND locked_by='bounded'),'batch cannot overclaim');
UPDATE bat_sale_replay_state SET started_at=now()-interval '20 minutes',last_finished_at=now()-interval '20 minutes';
SELECT fixture_assert(assay_bat_sale_intake()->>'status'='failed','stalled real backlog failed');
SELECT fixture_assert((SELECT count(*)=0 FROM pg_stat_activity WHERE wait_event_type='Lock'),'no leftover locks');
