#!/bin/bash
echo "🚀 Deploying to Production..."
echo ""
echo "Repository: https://github.com/sss97133/nuke.git"
echo "Platform: Vercel"
echo ""
echo "Steps:"
echo "1. Push changes to main branch"
echo "2. Vercel will auto-deploy"
echo ""
cd nuke_frontend
npm run build
echo ""
echo "✅ Production build ready at: nuke_frontend/dist/"
echo ""
echo "To deploy:"
echo "  git add ."
echo "  git commit -m 'Homepage realignment: remove subtitle, public feed, auth-gated actions'"
echo "  git push origin main"
echo ""
echo "Vercel will automatically deploy and make it available at:"
echo "  https://nuke.vercel.app (or your custom domain)"
