#!/usr/bin/env python3
"""
Nuke Sentinel Bootstrap Script
Deploys and runs the persistent monitoring agent on Orgo.
"""

import os
import json
import subprocess
from pathlib import Path
from datetime import datetime

# Try to import orgo SDK
try:
    from orgo import Computer
    HAS_ORGO = True
except ImportError:
    HAS_ORGO = False
    print("Warning: orgo SDK not installed. Run: pip install orgo")

AGENT_DIR = Path(__file__).parent
CONFIG_FILE = AGENT_DIR / "config.json"


def load_config():
    with open(CONFIG_FILE) as f:
        return json.load(f)


def check_prerequisites():
    """Verify all required APIs are accessible."""
    config = load_config()
    checks = []

    # Check Orgo
    orgo_key = os.getenv(config["orgo"]["api_key_env"])
    checks.append(("Orgo API Key", bool(orgo_key)))

    # Check Supabase
    supabase_url = os.getenv(config["nuke"]["supabase_url_env"])
    supabase_key = os.getenv(config["nuke"]["supabase_key_env"])
    checks.append(("Supabase URL", bool(supabase_url)))
    checks.append(("Supabase Key", bool(supabase_key)))

    print("\n=== Prerequisite Checks ===")
    all_pass = True
    for name, passed in checks:
        status = "OK" if passed else "MISSING"
        print(f"  {name}: {status}")
        if not passed:
            all_pass = False

    return all_pass


def create_sentinel_alerts_table():
    """Create alerts table in Supabase if not exists."""
    sql = """
    CREATE TABLE IF NOT EXISTS sentinel_alerts (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        created_at TIMESTAMPTZ DEFAULT NOW(),
        severity TEXT NOT NULL CHECK (severity IN ('critical', 'warning', 'info')),
        type TEXT NOT NULL,
        message TEXT NOT NULL,
        data JSONB DEFAULT '{}',
        acknowledged BOOLEAN DEFAULT FALSE,
        acknowledged_at TIMESTAMPTZ,
        acknowledged_by TEXT
    );

    CREATE INDEX IF NOT EXISTS idx_sentinel_alerts_unack
    ON sentinel_alerts (created_at DESC)
    WHERE acknowledged = FALSE;
    """
    print("\n=== Creating sentinel_alerts table ===")
    # This would be run via Supabase MCP or psql
    print("  SQL ready - run via Supabase MCP or migration")
    return sql


def seed_initial_tasks():
    """Ensure initial tasks exist."""
    tasks_dir = AGENT_DIR / "tasks"
    tasks = list(tasks_dir.glob("*.json"))
    print(f"\n=== Task Queue ===")
    print(f"  Found {len(tasks)} tasks")
    for t in tasks:
        with open(t) as f:
            task = json.load(f)
        print(f"  - {task['id']}: {task['type']} ({task['status']})")


def deploy_to_orgo():
    """Deploy agent to Orgo VM."""
    if not HAS_ORGO:
        print("\n=== Orgo Deployment ===")
        print("  Skipped - orgo SDK not installed")
        print("  Install with: pip install orgo")
        print("  Then run: python bootstrap.py --deploy")
        return None

    config = load_config()
    api_key = os.getenv(config["orgo"]["api_key_env"])

    if not api_key:
        print("  Error: ORGO_API_KEY not set")
        return None

    print("\n=== Deploying to Orgo ===")

    # Create computer instance
    computer = Computer(api_key=api_key)

    # The agent would run claude code in the VM
    # For now, return the computer instance
    print(f"  Computer instance created")
    return computer


def local_test_run():
    """Run a single cycle locally for testing."""
    print("\n=== Local Test Run ===")

    # Simulate tool-scout task
    print("  Running tool-scout...")

    # Would use web search here
    keywords = ["claude code", "anthropic mcp", "ai agent"]
    print(f"  Searching HN for: {keywords}")

    # Create sample report
    report_dir = AGENT_DIR / "reports"
    report_file = report_dir / f"tool-scout-{datetime.now().strftime('%Y%m%d-%H%M')}.md"

    sample_report = f"""# Tool Scout Report - {datetime.now().isoformat()}

## Search Parameters
- Keywords: {', '.join(keywords)}
- Sources: Hacker News, GitHub

## Status
- Local test run
- Full implementation requires web search API

## Next Steps
1. Deploy to Orgo for persistent running
2. Connect web search MCP
3. Enable alerting

---
Generated by nuke-sentinel bootstrap
"""

    with open(report_file, 'w') as f:
        f.write(sample_report)

    print(f"  Report written: {report_file.name}")


def main():
    import sys

    print("=" * 50)
    print("NUKE SENTINEL - Bootstrap")
    print("=" * 50)

    # Load and display config
    config = load_config()
    print(f"\nAgent: {config['agent']['name']} v{config['agent']['version']}")

    # Check prerequisites
    if not check_prerequisites():
        print("\n[!] Some prerequisites missing. Set environment variables.")
        print("    Export from nuke/.env or use dotenvx")

    # Show task queue
    seed_initial_tasks()

    # Show SQL for alerts table
    create_sentinel_alerts_table()

    # Handle commands
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd == "--deploy":
            deploy_to_orgo()
        elif cmd == "--test":
            local_test_run()
        elif cmd == "--help":
            print("\nUsage:")
            print("  python bootstrap.py          # Check setup")
            print("  python bootstrap.py --test   # Run local test")
            print("  python bootstrap.py --deploy # Deploy to Orgo")
    else:
        print("\n[i] Run with --test for local test or --deploy for Orgo")


if __name__ == "__main__":
    main()
