import Config

# Configure your database to use remote Supabase PostgreSQL via connection pooler
config :nuke_api, NukeApi.Repo,
  username: "postgres.qkgaybvrernstplzjaam",
  password: System.get_env("SUPABASE_DB_PASSWORD"),
  hostname: "aws-0-us-west-1.pooler.supabase.com",
  port: 5432,
  database: "postgres",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 5,
  timeout: 30_000,
  ownership_timeout: 30_000,
  pool_timeout: 10_000,
  queue_target: 200,
  queue_interval: 2_000,
  checkout_timeout: 15_000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :nuke_api, NukeApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "1iHogoOhhtleB8CJzOPWbAwc+grlPMo6pZ1T/f5Sg9M39WKa8hZO5NPpLFg/iChU",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:nuke_api, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:nuke_api, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :nuke_api, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure Supabase integration
config :nuke_api, :supabase,
  url: System.get_env("SUPABASE_URL") || "https://qkgaybvrernstplzjaam.supabase.co",
  api_key: System.get_env("SUPABASE_ANON_KEY"),
  jwt_secret: System.get_env("SUPABASE_JWT_SECRET")

# Add CORS configuration
config :nuke_api, NukeApiWeb.Endpoint,
  cors_plug_options: [
    origin: ["http://localhost:3000", "http://localhost:5173", "http://127.0.0.1:5173", "http://localhost:5174", "http://127.0.0.1:5174"],
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    headers: ["Authorization", "Content-Type", "Accept", "Origin", "User-Agent"],
    credentials: true,
    max_age: 86400
  ]
