#!/bin/sh

# Xcode Cloud post-clone step.
#
# NukeCapture-iOS.xcodeproj is generated by XcodeGen from project.yml and is
# gitignored, so a fresh clone on the Xcode Cloud runner has only project.yml —
# no .xcodeproj, no scheme. Without this, the build fails in ~seconds with
# "project not found." Install XcodeGen and generate the project (+ its shared
# scheme) before Xcode Cloud resolves packages and builds.
#
# Xcode Cloud runs with AUTOMATIC SwiftPM resolution DISABLED everywhere — even an
# explicit `xcodebuild -resolvePackageDependencies` is refused (build 29 attempt 2,
# 0445d81b: "ci_post_clone.sh failed (exit 74) … a resolved file is required when
# automatic dependency resolution is disabled"). So we cannot resolve on the runner
# at all; we must SHIP a Package.resolved and drop it into the generated workspace
# before the archive step. The committed copy lives next to project.yml
# (apps/nuke-capture-ios/Package.resolved); regenerate it after changing `packages:`
# with:  xcodegen generate && xcodebuild -resolvePackageDependencies … then copy the
# produced .xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved here.

set -e

echo "▸ Installing XcodeGen…"
brew install xcodegen

echo "▸ Generating NukeCapture-iOS.xcodeproj from project.yml…"
cd "$CI_PRIMARY_REPOSITORY_PATH/apps/nuke-capture-ios"
xcodegen generate

echo "▸ Seeding the committed Package.resolved into the generated workspace…"
SWIFTPM_DIR="NukeCapture-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
mkdir -p "$SWIFTPM_DIR"
cp Package.resolved "$SWIFTPM_DIR/Package.resolved"

echo "▸ Done. Project generated + Package.resolved seeded:"
ls -d NukeCapture-iOS.xcodeproj
ls -l "$SWIFTPM_DIR/Package.resolved"
