#!/bin/sh

# Xcode Cloud post-clone step.
#
# NukeCapture-iOS.xcodeproj is generated by XcodeGen from project.yml and is
# gitignored, so a fresh clone on the Xcode Cloud runner has only project.yml —
# no .xcodeproj, no scheme. Without this, the build fails in ~seconds with
# "project not found." Install XcodeGen and generate the project (+ its shared
# scheme) before Xcode Cloud resolves packages and builds.

set -e

echo "▸ Installing XcodeGen…"
brew install xcodegen

echo "▸ Generating NukeCapture-iOS.xcodeproj from project.yml…"
cd "$CI_PRIMARY_REPOSITORY_PATH/apps/nuke-capture-ios"
xcodegen generate

echo "▸ Done. Project generated:"
ls -d NukeCapture-iOS.xcodeproj
