#!/bin/sh

# Xcode Cloud post-clone step.
#
# NukeCapture-iOS.xcodeproj is generated by XcodeGen from project.yml and is
# gitignored, so a fresh clone on the Xcode Cloud runner has only project.yml —
# no .xcodeproj, no scheme. Without this, the build fails in ~seconds with
# "project not found." Install XcodeGen and generate the project (+ its shared
# scheme) before Xcode Cloud resolves packages and builds.
#
# Xcode Cloud runs the archive action with AUTOMATIC SwiftPM resolution DISABLED:
# it refuses to hit the network mid-build and instead requires a committed
# Package.resolved at
#   NukeCapture-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
# A freshly XcodeGen'd project has no such file, so the archive died with
# "a resolved file is required when automatic dependency resolution is disabled …
# Running resolver because the following dependencies were added: 'supabase-swift'"
# (build 29, e9e5401a). post_clone DOES have network, so we resolve here — that
# writes Package.resolved before the archive step runs.

set -e

echo "▸ Installing XcodeGen…"
brew install xcodegen

echo "▸ Generating NukeCapture-iOS.xcodeproj from project.yml…"
cd "$CI_PRIMARY_REPOSITORY_PATH/apps/nuke-capture-ios"
xcodegen generate

echo "▸ Resolving Swift package dependencies (writes the Package.resolved the archive step demands)…"
xcodebuild -resolvePackageDependencies \
  -project NukeCapture-iOS.xcodeproj \
  -scheme NukeCapture-iOS

echo "▸ Done. Project generated + packages resolved:"
ls -d NukeCapture-iOS.xcodeproj
ls -l NukeCapture-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
