#!/bin/bash
# Nightly regression scan — checks data integrity and extraction quality
# Usage: dotenvx run -- bash scripts/scheduled/nightly-regression.sh

set -uo pipefail
cd /Users/skylar/nuke

PGARGS="-h aws-0-us-west-1.pooler.supabase.com -p 6543 -U postgres.qkgaybvrernstplzjaam -d postgres -t -A"
export PGPASSWORD="RbzKq32A0uhqvJMQ"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M")
ISSUES=0

run_sql() {
  psql $PGARGS -c "$1" 2>/dev/null | tr -d ' ' | head -1
}

echo "## Nightly Regression — $TIMESTAMP"
echo ""

# 1. Data Integrity (lightweight queries — skip orphan joins on 32M row tables)
echo "### Data Integrity"

BAD_YEARS=$(run_sql "SELECT count(*) FROM vehicles WHERE year IS NOT NULL AND (year < 1700 OR year > 2027);")
DUPE_VINS=$(run_sql "SELECT count(*) FROM (SELECT vin FROM vehicles WHERE status = 'active' AND vin IS NOT NULL AND length(vin) = 17 GROUP BY vin HAVING count(*) > 1) x;")
NULL_STATUS=$(run_sql "SELECT count(*) FROM vehicles WHERE status IS NULL;")

[ "${BAD_YEARS:-0}" -gt 0 ] 2>/dev/null && { echo "- **WARNING**: $BAD_YEARS vehicles with invalid years"; ISSUES=$((ISSUES+1)); } || echo "- Bad years: 0"
[ "${DUPE_VINS:-0}" -gt 5 ] 2>/dev/null && { echo "- **WARNING**: $DUPE_VINS duplicate VIN groups"; ISSUES=$((ISSUES+1)); } || echo "- Duplicate VINs: ${DUPE_VINS:-0}"
[ "${NULL_STATUS:-0}" -gt 0 ] 2>/dev/null && { echo "- **WARNING**: $NULL_STATUS vehicles with NULL status"; ISSUES=$((ISSUES+1)); } || echo "- NULL status vehicles: 0"
echo ""

# 2. Field Fill Rates
echo "### Quality Metrics (active vehicles)"
FILL_RATES=$(psql $PGARGS -c "
SELECT json_build_object(
  'total', count(*),
  'year', round(100.0 * count(year) / NULLIF(count(*),0), 1),
  'make', round(100.0 * count(make) / NULLIF(count(*),0), 1),
  'model', round(100.0 * count(model) / NULLIF(count(*),0), 1),
  'vin', round(100.0 * count(vin) / NULLIF(count(*),0), 1),
  'price', round(100.0 * count(sale_price) / NULLIF(count(*),0), 1),
  'image', round(100.0 * count(primary_image_url) / NULLIF(count(*),0), 1)
) FROM vehicles WHERE status = 'active';
" 2>/dev/null | tr -d ' ')

if [ -n "$FILL_RATES" ] && echo "$FILL_RATES" | jq . >/dev/null 2>&1; then
  echo "- Total active: $(echo $FILL_RATES | jq -r '.total')"
  echo "- Year: $(echo $FILL_RATES | jq -r '.year')%"
  echo "- Make: $(echo $FILL_RATES | jq -r '.make')%"
  echo "- Model: $(echo $FILL_RATES | jq -r '.model')%"
  echo "- VIN: $(echo $FILL_RATES | jq -r '.vin')%"
  echo "- Price: $(echo $FILL_RATES | jq -r '.price')%"
  echo "- Image: $(echo $FILL_RATES | jq -r '.image')%"
else
  echo "- **WARNING**: Could not query fill rates"
  ISSUES=$((ISSUES+1))
fi
echo ""

# 3. Pipeline Flow (7 days)
echo "### Pipeline Flow (last 7 days)"
NEW_VEHICLES=$(run_sql "SELECT count(*) FROM vehicles WHERE created_at > now() - interval '7 days';")
COMPLETED_EXTRACTIONS=$(run_sql "SELECT count(*) FROM import_queue WHERE status = 'complete' AND updated_at > now() - interval '7 days';")

echo "- New vehicles: ${NEW_VEHICLES:-N/A}"
echo "- Completed extractions: ${COMPLETED_EXTRACTIONS:-N/A}"
if [ "${NEW_VEHICLES:-0}" = "0" ] 2>/dev/null; then
  echo "- **WARNING**: No new vehicles in 7 days!"
  ISSUES=$((ISSUES+1))
fi
echo ""

# 4. Recent Error Rate
echo "### Import Queue (last 7d)"
QUEUE_7D=$(psql $PGARGS -c "
SELECT json_build_object(
  'complete', count(*) FILTER (WHERE status = 'complete'),
  'failed', count(*) FILTER (WHERE status = 'failed'),
  'skipped', count(*) FILTER (WHERE status = 'skipped')
) FROM import_queue WHERE updated_at > now() - interval '7 days';
" 2>/dev/null | tr -d ' ')

if [ -n "$QUEUE_7D" ] && echo "$QUEUE_7D" | jq . >/dev/null 2>&1; then
  echo "- Complete: $(echo $QUEUE_7D | jq -r '.complete')"
  echo "- Failed: $(echo $QUEUE_7D | jq -r '.failed')"
  echo "- Skipped: $(echo $QUEUE_7D | jq -r '.skipped')"
else
  echo "- Could not query queue stats"
fi
echo ""

# 5. Overall Status
echo "### Overall Status"
if [ "$ISSUES" -eq 0 ]; then
  echo "**GREEN** — All checks passed"
elif [ "$ISSUES" -le 2 ]; then
  echo "**YELLOW** — $ISSUES warnings"
else
  echo "**RED** — $ISSUES issues found"
fi

echo ""
echo "---"
echo "*Generated by nightly-regression.sh*"
