#!/usr/bin/env bash
# generate.sh — the ONLY way to produce NukeCapture-iOS.xcodeproj before archiving.
#
# Why this exists: the .xcodeproj is generated by XcodeGen (gitignored), so the
# build number lives in project.yml. Pinning it there means every regenerate
# ships the same CFBundleVersion, and App Store Connect rejects any upload whose
# build number isn't strictly higher than the last accepted one — which is the
# bug that stalled 1.0.0 after build 27. This stamps a fresh, monotonic build
# number on every generate, so you never hand-bump it again.
#
# Build number = seconds since 2024-01-01 UTC. Always increases, never collides,
# and (unlike a git commit count) does not depend on clone depth — this repo
# clones shallow, which would make a commit-count build number unreliable.
#
#   cd apps/nuke-capture-ios && ./generate.sh && open NukeCapture-iOS.xcodeproj
set -euo pipefail
cd "$(dirname "$0")"

command -v xcodegen >/dev/null 2>&1 || { echo "❌ xcodegen not found — run: brew install xcodegen" >&2; exit 1; }

xcodegen generate

build_number="$(( $(date -u +%s) - 1704067200 ))"   # seconds since 2024-01-01 UTC
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${build_number}" Generated/Info.plist

echo "✅ NukeCapture-iOS.xcodeproj ready · CFBundleVersion ${build_number} (auto, monotonic) · MARKETING_VERSION from project.yml"
