// connector-inspector/PrintSkin.tsx — export door, not a view. The print set
// is generated by the existing pipeline (scripts/generate_connector_build_sheets.py
// via `npm run wiring:connector-sheets`); this skin just points at it.
// All chrome from the active Colorway.

import React from 'react';
import type { ConnectorModel } from './types';
import { frame, rule, useColorway } from './colorways';

const SHEETS: { file: string; covers: string }[] = [
  { file: 'K5_connector_FIREWALL_D38999', covers: 'FIREWALL BULKHEAD — D38999 25-61' },
  { file: 'K5_connector_M130A', covers: 'M130 CONN A — 34W SUPERSEAL' },
  { file: 'K5_connector_M130B', covers: 'M130 CONN B — 26W SUPERSEAL' },
  { file: 'K5_connector_PDM30', covers: 'PDM30 CONN A + B SUPERSEAL' },
];

export function PrintSkin({ model }: { model: ConnectorModel }) {
  const cw = useColorway();
  return (
    <div style={{ height: '100%', overflowY: 'auto', background: cw.bg, padding: '24px 28px', color: cw.ink, fontFamily: cw.fontBody }}>
      <div style={{ maxWidth: 760 }}>
        <div style={{ fontSize: 18, fontWeight: 700, letterSpacing: 1, marginBottom: 6 }}>
          PRINT SET — SHOP BUILD SHEETS
        </div>
        <div style={{ fontSize: 14, color: cw.inkMuted, lineHeight: 1.7, marginBottom: 18 }}>
          The bench print is a projection of the same data this inspector renders. Generate the
          full 4-sheet set (SVG → 2200×1700 PNG + merged PDF) from the repo root:
        </div>

        <div style={{
          border: frame(cw), background: cw.surface, padding: '12px 16px',
          fontFamily: cw.fontMono, fontSize: 15, color: cw.accent, marginBottom: 18,
        }}>
          cd /Users/skylar/nuke && npm run wiring:connector-sheets
        </div>

        <div style={{ fontSize: 14, fontWeight: 700, letterSpacing: 1, color: cw.inkMuted, marginBottom: 8 }}>
          OUTPUT — docs/wiring/output/connector-sheets/
        </div>
        <table style={{ borderCollapse: 'collapse', width: '100%', marginBottom: 18 }}>
          <tbody>
            {SHEETS.map(s => (
              <tr key={s.file} style={{ borderBottom: rule(cw), background: s.covers.startsWith(model.title.split(' —')[0]) ? cw.surface : 'transparent' }}>
                <td style={{ padding: '7px 10px', fontFamily: cw.fontMono, fontSize: 14, color: cw.ink, whiteSpace: 'nowrap' }}>
                  {s.file}.svg / .png
                </td>
                <td style={{ padding: '7px 10px', fontSize: 14, color: cw.inkMuted }}>{s.covers}</td>
              </tr>
            ))}
            <tr>
              <td style={{ padding: '7px 10px', fontFamily: cw.fontMono, fontSize: 14, color: cw.ink }}>
                K5_connector_build_sheets.pdf
              </td>
              <td style={{ padding: '7px 10px', fontSize: 14, color: cw.inkMuted }}>ALL FOUR SHEETS, MERGED — THE BENCH PACKET</td>
            </tr>
          </tbody>
        </table>

        <div style={{ fontSize: 14, color: cw.inkFaint, lineHeight: 1.7 }}>
          Sheets carry the title-block framing, cavity tables and overflow panel for the bench.
          Sources: scripts/generate_connector_build_sheets.py (MILNEC D38999 insert arrangement,
          TE Superseal 1.0 grids, PDM30 datasheet Part 14103). The FACE / TABLE / BUILD skins in
          this inspector are live views of the same cavity allocation.
        </div>
      </div>
    </div>
  );
}
