-- Expand `vehicle-models` allowed mime types to support annotation exports
-- (JSON/CSV) generated by the web-based harness drafting UI.

begin;

do $$
begin
  if to_regclass('storage.buckets') is null then
    raise notice 'Skipping vehicle-models mime update: storage.buckets does not exist.';
    return;
  end if;

  update storage.buckets
  set allowed_mime_types = array[
    'application/octet-stream',
    'application/zip',
    'application/json',
    'text/csv',
    'model/gltf-binary',
    'model/gltf+json',
    'application/x-fbx'
  ]::text[]
  where id = 'vehicle-models';
end
$$;

commit;


