-- Describe organization_vehicles: the 30 columns with no COMMENT ON COLUMN (10 of 40 described before, catalog count on
-- prod, 2026-10-07), seven corrected column comments and a corrected table comment. Comments only.
-- Describe stage of the repair loop (docs/ledger/theory/data-machine-cases.md section 12; data-machine.md
-- "the database describes itself"). Written table: 394,035 rows on 2026-10-07 02:25Z by exact count (the atlas estimate of
-- 348,077 is a stale pg_class.reltuples; pg_stat_user_tables shows no analyze time).
--
-- METHOD (read 2026-10-07 UTC):
--   Columns, types, defaults, constraints, indexes, policies, grants (has_column_privilege for anon) and existing comments
--   from pg_attribute, pg_constraint, pg_indexes, pg_policy, information_schema and pg_description. Fill, values and date
--   windows are exact counts over the whole table (70 MB heap, read only, one scan per query). The share of rows that match
--   the origin-organization trigger comes from an 8% block sample (TABLESAMPLE SYSTEM (8) REPEATABLE (20261007), 30,645
--   rows) joined to vehicles; the 8,381 rows whose vehicle is gone come from an index-only anti-join over the whole table.
--   "Filled" means non-NULL and, for text, non-blank; arrays count non-empty.
--   Writers come from code at origin/main 98001563d (supabase/functions, supabase/migrations, database, scripts,
--   nuke_frontend/src), git history (b8531b185 added the Bring a Trailer note in bat-simple-extract, deleted by 43b72deae
--   on 2026-03-07), the bodies of the 54 live public SQL functions that name the table (27 write it; 7 of those run from
--   enabled triggers on vehicles, bat_listings, external_listings, vehicle_images, organization_images, timeline_events and
--   vehicle_relationship_verifications; none is named by any of the 126 cron.job commands), the 3 triggers on the table,
--   write_receipts (no rows for this table), pg_stat_user_tables and pipeline_registry.
--   pipeline_registry has one table-level row (owner auto_link_vehicle_to_origin_org, declared 2026-10-07 by
--   20261007002507_declare_table_owners_1.sql) and no column rows; no row is added here because the registry already names the
--   writers, and this migration only describes.
-- LIMITS:
--   write_receipts and the table statistics do not date individual rows (pg_stat_user_tables counts 21,302 inserts since an
--   unreset counter, which is not a window). Rows are dated by created_at only. Attribution of a row to a writer is by its
--   stamps (notes, auto_matched_reasons, relationship_type, status) and by matching the trigger signature, so it is a
--   consistency test, not a record: 66% of the sampled rows match the origin-organization trigger and 77% carry no stamp at all.
--   The cause of the 8,381 rows with no vehicle is not established.
--   Quoted values are categorical codes, writer stamps and function names only: no names, handles, contacts, URLs, ids or amounts.
-- CHANGED EXISTING COMMENTS:
--   relationship_type: listed 8 of the 21 values the CHECK allows, omitted supplier_build (stored on 2 rows) and listed buyer and
--   storage (stored on none).
--   auto_tagged: said GPS or receipt matching; 249 rows have a GPS match and none a receipt match, while 392,528 rows are true.
--   listing_status: its value list implied a lifecycle; the default for_sale sits on 391,015 rows including platform links, and
--   only for_sale and sold are stored.
--   cost_basis: said internal only; anon holds SELECT and the select policies are true, so it is readable without signing in.
--   days_on_lot: said auto-calculated; it is recomputed only when a row is updated, and 340,927 for-sale rows still hold 0.
--   quality_flag: listed values the only writer (FlagProblemButton) does not write (needs_verification, incomplete_data).
--   hidden_from_public: said the vehicle is hidden from public listings; no policy, view or function reads it and the select
--   policies are true, so nothing is hidden.
--   Table comment: said only many-to-many; it now names the grain, the writers, the readers, the clocks and the gaps.

BEGIN;
SET LOCAL statement_timeout = '30s';
SET LOCAL lock_timeout = '5s';

COMMENT ON TABLE public.organization_vehicles IS
'The links between organizations and vehicles: one row per organization, vehicle and relationship_type (grain: one link; UNIQUE (organization_id, vehicle_id, relationship_type)). 394,035 rows on 2026-10-07 (the atlas estimate of 348,077 is a stale reltuples) for 303 organizations and 347,147 vehicles; the largest organization holds 35.8% of the rows, the top 5 hold 80.4% and the top 20 hold 89.7%. A vehicle has one link on 305,280 vehicles, two on 37,630 and up to ten. By relationship_type: consigner 228,389, sold_by 72,088, service_provider 56,788, auction_platform 34,955, owner 1,545, work_location 268, supplier_build 2. Almost every row is written by a trigger or an importer, not typed by a person: auto_tagged is true on 392,528. About 66% of an 8% block sample (30,645 rows, 2026-10-07) matches the signature of the trigger on vehicles auto_link_vehicle_to_origin_org (the pipeline_registry owner): organization = vehicles.origin_organization_id, relationship set from vehicles.profile_origin, status active, no notes. The rest come from the listing-sync triggers on bat_listings and external_listings, extract-bat-core, import-pcarmarket-listing, extract-cars-and-bids-core, three scripts that stamp auto_matched_reasons, one-off imports and a few dealer tools (see notes and relationship_type). 18 of the 40 columns hold only their default or NULL on every row: receipt_match_count, featured, internal_notes, location_on_lot, quality_flag, quality_notes, flagged_by_user_id, flagged_at, hidden_from_public, service_status, auto_matched_confidence and the seven user_confirmed, user_rejected and override_notes columns. Event time exists only in start_date, end_date and sale_date (8, 1 and 648 rows); created_at is ingest time, 2025-11-02 .. 2026-10-07, and no trigger maintains updated_at. Readers: the access checks vehicle_user_has_access() and user_can_edit_vehicle() give an active contributor of an organization access to every vehicle linked to it by any row, whatever its relationship_type or status; the profile loaders get_org_profile_fast() and get_vehicle_profile_data(); the views dealer_sales_summary, sold_vehicle_proof, supplier_vehicle_readiness, orgs_needing_investigation and vehicle_permissions_debug; the web app (linked organizations on the vehicle profile, dealer inventory, organization pages). 8,381 rows (2.1%) point at a vehicle that is not in vehicles, created 2025-11-02 .. 2026-03-15, although the foreign key is validated. Anyone, signed in or not, can read every column of every row (RLS select policies are true; anon holds SELECT), including cost_basis and linked_by_user_id; no write receipts exist for the table.';

-- ── Identity and keys ───────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.organization_vehicles.id IS
'Surrogate key of the link. Unit: none (uuid). Source: gen_random_uuid() default. Referenced by foreign keys (both ON DELETE CASCADE) from organization_vehicle_notifications.organization_vehicle_id and vehicle_relationship_verifications.organization_vehicle_id. The working key of a link is (organization_id, vehicle_id, relationship_type), which is UNIQUE. A link that scripts/backfill-ownership-classification.mjs reclassifies is deleted and inserted again, so it gets a new id (and loses its notifications and verifications), while apply_approved_verification() and normalize_org_vehicle_relationships() change relationship_type in place and keep the id. Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.organization_id IS
'Organization side of the link: an organizations.id, foreign key ON DELETE CASCADE (deleting the organization deletes its links; the creating file 20251101000009_organization_system_overhaul.sql pointed at businesses, which was renamed into organizations). NOT NULL. 303 distinct organizations (2026-10-07), very uneven: the largest holds 35.8% of the rows, the top 5 hold 80.4%, the top 20 hold 89.7%. The organization is the seller, consigner, shop, owner, platform or location that relationship_type names. Set by every writer, usually from vehicles.origin_organization_id, bat_listings.organization_id, external_listings.organization_id, bat_seller_monitors.organization_id or the signed-in dealer tool. Unit: none (uuid). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.vehicle_id IS
'Vehicle side of the link: a vehicles.id, foreign key ON DELETE CASCADE (validated, its triggers enabled), NOT NULL. 347,147 distinct vehicles (2026-10-07): 305,280 have one link, 37,630 two, 3,573 three and 664 four to ten. 8,381 rows (2.1%; 7,513 distinct ids) hold an id that is not in vehicles, all created 2025-11-02 .. 2026-03-15, which a validated foreign key should not allow; how they got there is not established. A vehicle merge moves the links to the surviving vehicle (merge_duplicate_vehicles() and merge_vehicle_into_primary_by_url() update vehicle_id and delete a link that would collide with an existing one); rehydrate_profile_merge() moves chosen links onto the new vehicle it creates. Unit: none (uuid). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.relationship_type IS
'Role of the organization for the vehicle, part of the key (UNIQUE with organization_id and vehicle_id), NOT NULL, no default. CHECK organization_vehicles_relationship_type_check allows 21 values (owner, consigner, service_provider, work_location, sold_by, storage, auction_platform, buyer, parts_supplier, fabricator, painter, upholstery, transport, inspector, collaborator, current_consignment, past_consignment, purchased_from, supplier_inventory, supplier_sold, supplier_build); the CHECK is NOT VALID, so older rows are unchecked and every insert and update is checked. Stored (2026-10-07): consigner 228,389, sold_by 72,088, service_provider 56,788, auction_platform 34,955 (the platform that ran the sale), owner 1,545, work_location 268, supplier_build 2; the other 14 values are on no row. The word is the writer view, not a verified relationship. The origin-organization trigger derives it from vehicles.profile_origin (bat_import and url_scraper give consigner, dropbox_import gives owner, anything else service_provider); the listing-sync triggers write sold_by for the seller organization and auction_platform for the platform; extract-bat-core classifies the BaT seller description into owner, consigner, supplier_build or sold_by; GPS photo matching writes work_location; timeline events write service_provider. Some writers pass values the CHECK rejects, so those inserts are rejected whenever they run and no row holds them: complete-bat-import and link_org_from_timeline_event() (purchase events) write seller, and EnhancedDealerInventory and DealerBulkEditor write in_stock or a vehicle status. Unit: none. Grain: one link. Clock: n/a.';

-- ── Lifecycle, dates and sale ───────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.organization_vehicles.status IS
'Lifecycle word of the link, CHECK in (active, past, pending, sold, archived), default active. It mixes two meanings: the link ending (past, archived) and the vehicle selling (sold). Stored (2026-10-07): active 391,006, sold 2,485, past 538, archived 6, pending none. Writers: every insert path leaves or sets active; sync_bat_listing_to_organization_vehicles() sets sold on the seller link when the BaT listing has a sale_price; auto_mark_vehicle_sold_from_external_listing() sets past when an external listing is sold; apply_approved_verification() sets sold or the approved proposed status; normalize_org_vehicle_relationships() sets archived (the 6 archived rows, 2025-12-15). Overwritten in place, with no history. It disagrees with listing_status on some rows: 44 rows are sold here and for_sale there, 42 are sold there and active here. Unit: none. Grain: one link. Clock: state as of the last write (updated_at is not reliable, see that column).';
COMMENT ON COLUMN public.organization_vehicles.start_date IS
'Date the relationship began, as a writer stated it. Filled on 8 of 394,035 rows (2026-10-07), written 2025-11-02 and 2025-12-05 (one owner link and seven service_provider links). Code that can set it: link_org_from_timeline_event() writes the timeline event date (keeping the earlier date on a conflict) and forensicReceiptService.ts writes today for a new service_provider link; no importer, listing trigger or the origin-organization trigger sets it, and the writer of the 8 filled rows is not identified. NULL on 99.998% of rows, so it cannot date a consignment or a sale. Unit: calendar date, no time zone. Grain: one link. Clock: event time (start of the relationship, as stated).';
COMMENT ON COLUMN public.organization_vehicles.end_date IS
'Date the relationship ended, as a writer stated it. Filled on 1 of 394,035 rows (2026-10-07), an owner link whose status is sold, created 2025-11-02 together with a start_date; no writer in the repo sets it. Unit: calendar date, no time zone. Grain: one link. Clock: event time (end of the relationship, as stated).';
COMMENT ON COLUMN public.organization_vehicles.listing_status IS
'Sale state of the vehicle at this organization, CHECK in (for_sale, sold, pending, new_arrival, in_build, auction_soon, consignment, trade_in, parts_car, archived), default for_sale. The default lands on every insert that does not set it, including consigner, platform and service links where no sale is meant: for_sale 391,015 rows and sold 3,020 (2,977 of them sold_by links, 2026-10-07); the other 8 values are on no row. Writers of sold: auto_mark_vehicle_sold_from_external_listing(), apply_approved_verification() (an approved sale verification), backfill_sold_status_from_external_listings() and backfill_sold_vehicles_comprehensive(); EnhancedDealerInventory changes it in bulk. new_arrival is moved to for_sale after 3 days by auto_expire_new_arrivals(), run daily at 02:00 UTC by the GitHub workflow expire-new-arrivals.yml (latest run 2026-10-07 02:14Z), and has nothing to move. Read by the views dealer_sales_summary and sold_vehicle_proof. Unit: none. Grain: one link. Clock: state as of the last write.';
COMMENT ON COLUMN public.organization_vehicles.sale_date IS
'Day the vehicle sold through this link, as the writer derived it. Filled on 648 rows (0.16%; 2014-04-26 .. 2026-02-24, 2026-10-07): 537 sold_by links with status past, 78 sold_by with status sold, 17 work_location, 8 owner, 6 consigner and 1 service_provider, all with listing_status sold. Writers: auto_mark_vehicle_sold_from_external_listing() (external_listings.sold_at, else end_date, else the run date; since 20261006234500 it leaves the day alone when sold_at is the importer write clock), apply_approved_verification() for an approved sale verification, the two sold backfill functions and the dealer tools. 402 of the 648 days fall after the date the row was created and 246 on or before it. The check constraint sold_requires_proof that 20251121000002 declares is not on prod, so a sold status needs no date: 95 rows hold a sale_date without a sale_price and 39 a sale_price without a sale_date. Unit: calendar date, no time zone. Grain: one link. Clock: event time (sale day).';
COMMENT ON COLUMN public.organization_vehicles.sale_price IS
'What the vehicle sold for through this link, by name. Filled on 592 rows (0.15%, 2026-10-07): 571 sold_by links, 9 work_location, 7 consigner and 5 owner; 3 values are under 100. Writers: auto_mark_vehicle_sold_from_external_listing() stores external_listings.final_price, and when that is NULL the current bid, so a sold lot without a final price carries its last bid (it accounts for the 532 rows with status past); the other 60 rows were created 2025-11-02 .. 2025-12-29 by writers not identified (dealer tools or manual imports). No amount is quoted here. Unit: USD by name (numeric, no currency column). Grain: one link. Clock: event time (sale), dated by sale_date, which is NULL on 39 of these rows.';
COMMENT ON COLUMN public.organization_vehicles.days_on_lot IS
'Whole days between created_at and the last recompute, by update_days_on_lot() (trigger trg_update_days_on_lot, BEFORE UPDATE only): it runs when a row is updated and its listing_status is for_sale, new_arrival, in_build or consignment, and sets the day count of now() minus created_at. An insert never sets it (default 0), and nothing recomputes it on a schedule, so it is a snapshot as of the last update of that row, not a live count. 340,927 for_sale rows hold 0 (2026-10-07). 50,109 rows hold a value above 0, and 49,498 of them imply a recompute on 2026-02-15 or 2026-02-16 (created_at plus days_on_lot), a bulk update that left updated_at untouched (49,912 of the 50,109 still have updated_at equal to created_at). The repo migration 20251122150001_days_on_lot_calculator.sql (first photo date) is not what prod runs. Read by the view dealer_sales_summary (average days to sell). Unit: days (integer). Grain: one link. Clock: as of the last update of the row.';

-- ── How the link was made ───────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.organization_vehicles.auto_tagged IS
'True when a program, not a person, wrote the link; default false, never NULL. True on 392,528 rows (99.6%) and false on 1,507 (2026-10-07). The old text said GPS or receipt matching, but only 249 rows carry a GPS match and none a receipt match; the true rows come from the origin-organization trigger on vehicles, the listing-sync triggers on bat_listings and external_listings, extract-bat-core, the PCarMarket and Cars and Bids importers and the batch scripts that stamp auto_matched_reasons. The false rows are one-off batches of a few hundred on single days between 2025-11-02 and 2026-01-23 (the dealer Dropbox import, a dealer profile import script, and unattributed inserts on 2025-12-29, 2026-01-21 and 2026-01-22); link_org_from_timeline_event() also writes false. Read by should_show_in_user_profile() (an auto-tagged active link weakens a personal ownership claim) and by the vehicle profile loader. Unit: boolean. Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.linked_by_user_id IS
'Signed-in account that created or triggered the link, foreign key to auth.users.id (no ON DELETE action). Filled on 430 rows (0.11%, 2026-10-07), all from one account: work_location 215, service_provider 167, owner 47 and sold_by 1, created 2025-11-02 .. 2026-06-26. No consigner or auction_platform row has one. Writers: auto_tag_organization_from_gps() writes the uploader of the photo (vehicle_images.user_id), link_org_from_timeline_event() the timeline event user, auto_link_vehicle_to_origin_org() vehicles.uploaded_by, auto_tag_organization_from_receipt() (no trigger runs it) the receipt uploader, the RPCs link_organization_to_vehicle_from_url(), suggest_vehicle_organization_assignments() and approve_pending_assignment() the calling user, and forensicReceiptService.ts the signed-in user. A personal identifier that anon can read (see the table comment). Unit: none (uuid, auth.users). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.notes IS
'Free text left by the writer, in practice a stamp of where the link came from. Filled on 60,822 rows (15.4%, 2026-10-07). Shapes, with count and producer: External listing: <platform> 32,459 (sync_external_listing_to_organization_vehicles(), auction_platform and sold_by links, 2026-02-09 .. 2026-03-15); Imported from Bring a Trailer: <url> 16,418 (consigner links of one organization, written by the edge function bat-simple-extract, deleted 2026-03-07; 2026-01-24 .. 2026-02-17); Imported from PCarMarket: <url> 5,352 (import-pcarmarket-listing, 2025-12-22 .. 2026-02-14); Historical CL listing 3,503 (migration 20260130_link_craigslist_vehicles.sql, 2026-01-30); BaT listing 2,565 (sync_bat_listing_to_organization_vehicles(), 2026-02-09 .. 2026-07-26); Imported from Fantasy Junction BaT profile extraction 381 (scripts/extract-and-import-fantasy-junction-listings.js, 2026-01-09 .. 2026-01-10); Imported from Cars & Bids: <url> 56 (extract-cars-and-bids-core or scripts/extract-cab-vehicles-playwright.mjs); Dealer inventory - imported from Dropbox: <folder> 49 (DealerDropboxImport.tsx, 2025-11-02); Linked from URL 24 (link_organization_to_vehicle_from_url(), 2026-01-23); and 15 one-off notes from manual, GPS and timeline-event links. NULL or blank on the other 84.6%: the origin-organization trigger, extract-bat-core and the auto_matched_reasons scripts write none. A URL inside a note is the listing page, a source pointer and not a quote. Unit: none (text). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.auto_matched_confidence IS
'Confidence of an automatic match, 0 .. 1 (real). NULL on every row (2026-10-07). Added by 20251206_user_override_columns.sql; the only code that writes it is forensicReceiptService.ts (browser-side receipt analysis, with auto_matched_reasons and auto_matched_at), and no row carries a value or its note Auto-linked via forensic analysis, so neither its insert nor its update path has written a row here. The three scripts that stamp auto_matched_reasons do not set it. Unit: probability, 0 .. 1 (real), unlike gps_match_confidence, which is a percent. Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.auto_matched_reasons IS
'Why a program linked the organization to the vehicle: a text array that holds one writer stamp and never more than one. Filled on 32,620 rows (8.3%, 2026-10-07): dealer_auto_discovery 22,544 (sold_by, 2026-04-01, scripts/discover-dealer-sellers.mjs), bat_seller_monitor_match 7,084 (sold_by, 2026-03-29 .. 2026-04-01, scripts/backfill-bat-seller-to-org.mjs), description_regex_classifier 1,416 (consigner 768, owner 646, supplier_build 2; 2026-03-29; scripts/backfill-ownership-classification.mjs, which deletes the sold_by row and writes the reclassified one), description_regex_v2 1,128 (consigner 826, owner 302; 2026-03-31) and description_regex_v2_seller_reports 448 (owner; 2026-03-31); the code that wrote the last two stamps is not in the repo. NULL on every other row, so absence does not mean a person made the link: 77% of the sampled rows (8% block sample, 2026-10-07) carry neither this nor a note. Added by 20251206_user_override_columns.sql. Unit: none (text array of stamps). Grain: one link. Clock: set together with auto_matched_at.';
COMMENT ON COLUMN public.organization_vehicles.auto_matched_at IS
'When the script that stamped auto_matched_reasons made the match: each writer passes its own run time. Filled on the same 32,620 rows as auto_matched_reasons (2026-10-07), 2026-03-29 .. 2026-04-01, on the same calendar day as created_at in every stamp group; 186 distinct values (ANALYZE statistics). Added by 20251206_user_override_columns.sql. Unit: timestamptz. Grain: one link. Clock: ingest time (the script run).';
COMMENT ON COLUMN public.organization_vehicles.gps_match_confidence IS
'How close the photo that triggered the link was to the organization, as a percent. Filled on 249 rows (0.06%, 2026-10-07; service_provider and work_location links created 2025-11-02 .. 2026-06-26), range 1.00 .. 99.98. Writers: auto_tag_organization_from_gps() (trigger trg_auto_tag_org_from_gps on vehicle_images rows with a latitude and longitude) takes the nearest organization within 500 m of the photo, computes (1 - distance_km / 0.5) * 100 clamped to 0 .. 100 and keeps the larger value on a repeat; the RPCs suggest_vehicle_organization_assignments() and approve_pending_assignment() (no trigger or cron job calls them) write the same column from an overall_confidence score of calculate_vehicle_org_assignment_confidence(). numeric(4,2) holds at most 99.99, so the 100 the formula gives at zero distance does not fit. Shown on the vehicle profile (LinkedOrganizations). Unit: percent, 0 .. 100 (numeric(4,2)). Grain: one link. Clock: as of the last matching photo.';
COMMENT ON COLUMN public.organization_vehicles.receipt_match_count IS
'Number of receipts that matched the organization to the vehicle, default 0. 0 on all 394,035 rows (2026-10-07; never NULL). The only writer, auto_tag_organization_from_receipt() (sets 1 on insert and adds 1 on a repeat, for a receipt vendor name within trigram similarity 0.5 of an organization name), is attached to no trigger and named by no cron job, and no row holds a count above 0. Unit: count of receipts (integer). Grain: one link. Clock: n/a.';

-- ── Dealer inventory fields ─────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.organization_vehicles.cost_basis IS
'What the dealer paid for the vehicle, by name. The old text said internal only, but anon holds SELECT on every column and both select policies are true, so anyone can read it without signing in (has_column_privilege, 2026-10-07). Filled on 14 rows (0.004%): consigner 9, owner 2, work_location 2, sold_by 1, all created on 2025-11-02, the day of the dealer Dropbox import (writer not identified); migration 20260208200000 copies the column when it merges duplicate BaT organizations. Read by the view dealer_sales_summary (profit and inventory investment per organization; anon cannot select that view). No amount is quoted here. Unit: USD by name (numeric, no currency column). Grain: one link. Clock: n/a (as of the insert).';
COMMENT ON COLUMN public.organization_vehicles.featured IS
'Whether the dealer pinned the vehicle as featured, default false, never NULL. False on all 394,035 rows (2026-10-07). No code writes it; the dealer inventory page (EnhancedDealerInventory.tsx) selects it and shows a FEATURED label when true, so none shows. No migration in the repo adds the column; it is first named in 20251122150003_inventory_current_filter.sql. Unit: boolean. Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.internal_notes IS
'Notes for the organization staff that a public page should not show, by name. NULL or blank on every row (2026-10-07); no code reads or writes it and no migration in the repo adds it. Anon can read it like every column (see the table comment), so the name promises more privacy than the database gives. Unit: none (text). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.location_on_lot IS
'Where on the dealer lot the vehicle sits, by name. NULL or blank on every row (2026-10-07); no code, view or migration in the repo names it. Unit: none (text). Grain: one link. Clock: n/a.';

-- ── Quality flags and visibility ────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.organization_vehicles.quality_flag IS
'Problem flag a person put on the link, free text with no CHECK; partial index idx_org_vehicles_quality_flag. The only writer is the flag button on the dealer inventory page (FlagProblemButton.tsx), which writes duplicate, wrong_org, incomplete or spam (the old text listed needs_verification and incomplete_data, which nothing writes), together with flagged_by_user_id, flagged_at and hidden_from_public, and clears all four when it unflags. NULL on every row (2026-10-07), so no flag is standing; a cleared flag looks the same as no flag. No SQL function that names the table reads it. Unit: none (text). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.quality_notes IS
'Free-text explanation of a quality flag. NULL or blank on every row (2026-10-07); FlagProblemButton.tsx does not write it and no other code or migration in the repo names it for this table. Unit: none (text). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.flagged_by_user_id IS
'Account that flagged the link, a user id with no foreign key. NULL on every row (2026-10-07). Written by FlagProblemButton.tsx with quality_flag and cleared when it unflags, so it holds a value only while a flag stands. Anon can read it. Unit: none (uuid). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.flagged_at IS
'When the link was flagged: FlagProblemButton.tsx writes the browser time with quality_flag and clears it on unflag. NULL on every row (2026-10-07). Unit: timestamptz. Grain: one link. Clock: event time (the flagging).';
COMMENT ON COLUMN public.organization_vehicles.hidden_from_public IS
'Flag meant to keep the link off public pages until a problem is fixed; default false, never NULL; false on all 394,035 rows (2026-10-07). FlagProblemButton.tsx sets it true when it flags a link and false when it unflags. Nothing enforces it: no policy, view or SQL function reads it, no web code filters on it, and the select policies are true, so a hidden link would still be returned to anyone. The partial index idx_org_vehicles_hidden covers only true. Unit: boolean. Grain: one link. Clock: n/a.';

-- ── User confirmation (declared, never used) ────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.organization_vehicles.user_confirmed IS
'Whether a person confirmed the automatic link, default false, never NULL. False on all 394,035 rows (2026-10-07). Added by 20251206_user_override_columns.sql for a confirm-or-reject review of automatic links. The only code that touches it is forensicReceiptService.ts, which reads it so that a person override wins over a later automatic update and writes false on a new link; nothing writes true. Unit: boolean. Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.user_confirmed_by IS
'Account that confirmed the link, foreign key to auth.users.id. NULL on every row (2026-10-07); no code writes it. Added by 20251206_user_override_columns.sql. Unit: none (uuid). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.user_confirmed_at IS
'When the confirmation happened. NULL on every row (2026-10-07); no code writes it. Added by 20251206_user_override_columns.sql. Unit: timestamptz. Grain: one link. Clock: event time (the confirmation).';
COMMENT ON COLUMN public.organization_vehicles.user_rejected IS
'Whether a person rejected the automatic link, default false, never NULL. False on all 394,035 rows (2026-10-07). Added by 20251206_user_override_columns.sql. forensicReceiptService.ts reads it, skips a link a person rejected and never recreates it; nothing writes true, so the rejection path has never been used. Unit: boolean. Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.user_rejected_by IS
'Account that rejected the link, foreign key to auth.users.id. NULL on every row (2026-10-07); no code writes it. Added by 20251206_user_override_columns.sql. Unit: none (uuid). Grain: one link. Clock: n/a.';
COMMENT ON COLUMN public.organization_vehicles.user_rejected_at IS
'When the rejection happened. NULL on every row (2026-10-07); no code writes it. Added by 20251206_user_override_columns.sql. Unit: timestamptz. Grain: one link. Clock: event time (the rejection).';
COMMENT ON COLUMN public.organization_vehicles.override_notes IS
'Free-text reason a person gave for confirming or rejecting a link. NULL or blank on every row (2026-10-07); no code writes it. Added by 20251206_user_override_columns.sql. Unit: none (text). Grain: one link. Clock: n/a.';

-- ── Clocks ──────────────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.organization_vehicles.created_at IS
'When the link row was inserted: default now(), set by the database. 2025-11-02 .. 2026-10-07 (read 2026-10-07 02:25Z). By month: 2025-11 92, 2025-12 3,792, 2026-01 69,607, 2026-02 22,680, 2026-03 74,472, 2026-04 65,190, 2026-05 36,973, 2026-06 7,417, 2026-07 34,217, 2026-08 2,459, 2026-09 70,447; 35,384 rows on 2026-09-28 and 26,367 on 2026-09-29 (a burst of new vehicles through the origin-organization trigger), then 700 .. 2,100 a day, mostly service_provider links. This is ingest time of the link, not the date the organization and the vehicle became related: the event-time columns are start_date, end_date and sale_date. Bulk inserts share one day. Unit: timestamptz. Grain: one link. Clock: ingest time.';
COMMENT ON COLUMN public.organization_vehicles.updated_at IS
'Default now() at insert, set to now() by writers that update the row explicitly (the ON CONFLICT DO UPDATE paths, merge and verification functions, FlagProblemButton.tsx, complete-bat-import). No trigger maintains it. It differs from created_at on 726 rows (0.18%, 2026-10-07), none created since 2026-07, so it is not a last-modified time: a bulk update on 2026-02-15 and 2026-02-16 recomputed days_on_lot on about 49,500 rows and left updated_at unchanged. Unit: timestamptz. Grain: one link. Clock: ingest time of the insert, or the last explicit write.';

DO $$
DECLARE
  missing text;
BEGIN
  SELECT string_agg(a.attname, ', ' ORDER BY a.attnum) INTO missing
  FROM pg_attribute a
  WHERE a.attrelid = 'public.organization_vehicles'::regclass
    AND a.attnum > 0
    AND NOT a.attisdropped
    AND col_description(a.attrelid, a.attnum) IS NULL;
  IF missing IS NULL THEN
    RAISE NOTICE 'organization_vehicles: every column has a comment';
  ELSE
    RAISE NOTICE 'organization_vehicles columns still without a comment: %', missing;
  END IF;
END
$$;

COMMIT;
