-- Structural Keys lane: one existing bridge, atomic with the observation log.
-- Live 2026-10-02: witness observation FK and unique triple exist, image FK does
-- not. Latest 1,000 witnesses: 0 orphan/mismatched image links. Latest 1,000
-- observations: 687 valid same-vehicle JSON image links and 0 typed witnesses.
-- No historical rewrite/validation/backfill. NOT VALID protects new references.
-- P0.5 remains partial: legacy anonymous shop/professional_review intake still
-- allows extra JSON keys. Exclude that exact path from automatic projection;
-- this migration neither fixes its auth/quarantine gap nor promotes proposals.
SET statement_timeout = '30s';
SET lock_timeout = '5s';

ALTER TABLE public.observation_witnesses
  ADD CONSTRAINT observation_witnesses_image_id_fkey
  FOREIGN KEY (image_id) REFERENCES public.vehicle_images(id) NOT VALID;

COMMENT ON TABLE public.observation_witnesses IS
'Image-to-observation bridge. Grain: one observation × canonical image × witness role. Observation and image IDs are foreign keys; new log inserts append derived edges atomically. This relation is provenance, not calibrated proof or independent-source count. RLS stays deny-by-default; get_field_provenance is the vehicle-gated reader.';
COMMENT ON COLUMN public.observation_witnesses.id IS 'Bridge row UUID at observation × image × role grain; generated by Postgres, not a source event identity.';
COMMENT ON COLUMN public.observation_witnesses.observation_id IS 'Foreign key to immutable vehicle_observations testimony; source, method, trust, observed_at/event time and ingested_at/ingest time live on that observation.';
COMMENT ON COLUMN public.observation_witnesses.image_id IS 'Canonical vehicle_images UUID foreign key, never an arbitrary URL or filename. Insert projection requires the same non-null vehicle key as the observation. Image FK is NOT VALID for historical rows; new references are enforced.';
COMMENT ON COLUMN public.observation_witnesses.witness_role IS 'Relation vocabulary: primary, context, supersession, derived. Automatic JSON image-reference projection emits derived only; it does not infer that an image supports or proves the claimed value.';
COMMENT ON COLUMN public.observation_witnesses.capture_method IS 'Capture attestation vocabulary: live_streaming, photo_with_exif, photo_no_exif, composite, unknown. Automatic projection emits unknown; observed/review time does not prove capture method.';
COMMENT ON COLUMN public.observation_witnesses.image_timestamp IS 'Image capture event time, timestamptz; unknown is NULL. Automatic projection leaves NULL and never copies observation review or ingest time into a capture clock.';
COMMENT ON COLUMN public.observation_witnesses.attestation_notes IS 'Source/method limitations for this relation; automatic projection records a fixed provenance explanation, not generated visual findings.';
COMMENT ON COLUMN public.observation_witnesses.added_by_user_id IS 'Actual submitting user UUID when recorded on vehicle_observations; FK to auth.users. NULL means actor identity unknown, never a guessed owner.';
COMMENT ON COLUMN public.observation_witnesses.added_by_agent_key IS 'Producer attribution identifier, not a credential. Automatic projection records the explicit db:project_observation_image_witness:v1 method marker when no submitting user is recorded; it does not invent an agent/person/model identity.';
COMMENT ON COLUMN public.observation_witnesses.added_at IS 'Bridge ingestion time, timestamptz, default Postgres now(); distinct from observation observed_at and image capture event time.';

CREATE OR REPLACE FUNCTION public.project_observation_image_witness()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
SET search_path = '' SET lock_timeout = '5s'
AS $projection$
DECLARE
  image_reference text;
  image_key uuid;
  image_vehicle uuid;
BEGIN
  -- Exact legacy share-verdict path is not authenticated testimony promotion.
  IF NEW.kind::text = 'comment'
     AND NEW.structured_data->>'kind_detail' = 'professional_review'
     AND EXISTS (SELECT 1 FROM public.observation_sources s
                 WHERE s.id = NEW.source_id AND s.slug = 'shop') THEN
    RETURN NEW;
  END IF;
  image_reference := NEW.structured_data->>'image_id';
  IF image_reference IS NULL OR lower(btrim(image_reference)) = 'unknown' THEN
    RETURN NEW;
  END IF;
  IF image_reference !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'observation_image_reference_invalid';
  END IF;
  image_key := image_reference::uuid;
  -- FOR SHARE prevents a concurrent non-key vehicle reassignment while this
  -- same-vehicle relation is checked and appended. One image row, fixed cost.
  SELECT i.vehicle_id INTO image_vehicle FROM public.vehicle_images i
    WHERE i.id = image_key FOR SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'observation_image_reference_missing';
  END IF;
  IF NEW.vehicle_id IS NULL OR image_vehicle IS NULL OR NEW.vehicle_id <> image_vehicle THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'observation_image_vehicle_mismatch';
  END IF;
  INSERT INTO public.observation_witnesses (
    observation_id, image_id, witness_role, capture_method, image_timestamp,
    attestation_notes, added_by_user_id, added_by_agent_key
  ) VALUES (
    NEW.id, image_key, 'derived', 'unknown', NULL,
    'Derived from structured_data.image_id by the observation log insert projection; no assertion of visual correctness, independent source, capture method or capture time.',
    NEW.submitted_by_user_id,
    CASE WHEN NEW.submitted_by_user_id IS NULL THEN 'db:project_observation_image_witness:v1' END
  ) ON CONFLICT (observation_id, image_id, witness_role) DO NOTHING;
  RETURN NEW;
END
$projection$;
COMMENT ON FUNCTION public.project_observation_image_witness() IS
'Atomic append projection for new vehicle_observations only. Grain: one validated same-vehicle image reference per observation, witness_role derived; uniqueness makes receipt replay idempotent. Invalid/nonexistent/cross-vehicle references abort the observation transaction. Missing/unknown references and the legacy anonymous shop professional-review path produce no witness. No historical replay or visual/model inference.';
REVOKE ALL ON FUNCTION public.project_observation_image_witness() FROM PUBLIC;
CREATE TRIGGER trg_project_observation_image_witness
AFTER INSERT ON public.vehicle_observations
FOR EACH ROW WHEN (NEW.structured_data ? 'image_id')
EXECUTE FUNCTION public.project_observation_image_witness();

INSERT INTO public.pipeline_registry
  (table_name, column_name, owned_by, description, do_not_write_directly, write_via)
VALUES ('observation_witnesses', 'image_id', 'project_observation_image_witness',
  'Owns automatic derived links from new vehicle_observations JSON image IDs; atomic trigger, no API/model calls. Assay: eligible arrivals after deployment must each have one derived witness; historical/quarantine/share exclusions remain explicit. No scheduled cadence/health reader registered by this migration.',
  true, 'vehicle_observations insert via ingest-observation; trg_project_observation_image_witness');

CREATE OR REPLACE FUNCTION public.get_field_provenance(p_vehicle_id uuid, p_field text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  with gate as (
    select v.* from public.vehicles v
    where v.id = p_vehicle_id
      and (v.is_public = true
           or auth.uid() in (v.user_id, v.owner_id, v.uploaded_by))
  ),
  prov as (
    select primary_source, total_confidence
    from public.vehicle_field_provenance
    where vehicle_id = p_vehicle_id and field_name = p_field
    limit 1
  ), visible_images as materialized (
    select i.id, i.image_url
    from public.vehicle_images i
    where i.vehicle_id = p_vehicle_id and exists (select 1 from gate)
      and nullif(btrim(i.image_url), '') is not null
      and i.is_sensitive is not true and i.is_superseded is not true
      and i.is_duplicate is not true
      and (i.vision_gate_status is null or i.vision_gate_status::text = 'approved')
      and coalesce(i.image_vehicle_match_status, '') not in ('mismatch', 'unrelated')
  ), field_observations as materialized (
    select o.*, s.slug as source_slug, s.base_trust_score as source_trust,
           case when o.structured_data->>'image_id'
             ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             then (o.structured_data->>'image_id')::uuid end as legacy_image_id
    from public.vehicle_observations o
    left join public.observation_sources s on s.id = o.source_id
    where o.vehicle_id = p_vehicle_id and o.is_superseded is not true
      and o.structured_data ? p_field
  ), image_observations as (
    -- Typed derived edges are authoritative when present. Visibility is checked
    -- again at read time; a hidden typed edge must not reopen a JSON fallback.
    select o.*, w.id as witness_id, w.witness_role,
           i.id as visible_image_id, i.image_url as visible_image_url
    from field_observations o
    join public.observation_witnesses w on w.observation_id = o.id and w.witness_role = 'derived'
    join visible_images i on i.id = w.image_id
    union all
    select o.*, null::uuid as witness_id, null::text as witness_role,
           i.id as visible_image_id, i.image_url as visible_image_url
    from field_observations o
    join visible_images i on i.id = o.legacy_image_id
    where not exists (select 1 from public.observation_witnesses w
      where w.observation_id = o.id and w.witness_role = 'derived')
  ), readable_observations as (
    select o.* from field_observations o
    where (not (o.structured_data ? 'image_id') and not exists (
      select 1 from public.observation_witnesses w
      where w.observation_id = o.id and w.witness_role = 'derived'))
      or exists (select 1 from image_observations i where i.id = o.id)
  )
  select case when not exists (select 1 from gate) then null else jsonb_build_object(
    'field', p_field,
    'vehicle_id', p_vehicle_id,
    'value',             (select to_jsonb(g)->>p_field                          from gate g),
    -- inline source falls back to the consensus primary_source (vehicle_field_provenance)
    'inline_source', coalesce(
        (select to_jsonb(g)->>(p_field||'_source')     from gate g),
        (select primary_source from prov)),
    'inline_confidence', coalesce(
        (select to_jsonb(g)->>(p_field||'_confidence') from gate g),
        (select total_confidence::text from prov)),
    -- source image falls back to the cited field_evidence row's photo
    'source_image_url', coalesce(
        (select i.image_url from visible_images i
          where i.id = case
            when (select to_jsonb(g)->>(p_field||'_source_image_id') from gate g)
              ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            then (select to_jsonb(g)->>(p_field||'_source_image_id') from gate g)::uuid end),
        (select i.image_url from public.field_evidence fe
          join visible_images i on
            i.id = case when fe.raw_extraction_data->>'photo_id'
              ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
              then (fe.raw_extraction_data->>'photo_id')::uuid end
            or (not (fe.raw_extraction_data ? 'photo_id')
                and i.image_url = fe.raw_extraction_data->>'image_url')
          where fe.vehicle_id = p_vehicle_id and fe.field_name = p_field
            and fe.status <> 'superseded' and fe.status not like 'rejected%'
          order by fe.source_confidence desc nulls last limit 1)),
    -- evidence = vehicle_field_sources ∪ field_evidence (the consensus pipeline), highest confidence first
    'evidence', coalesce((
        select jsonb_agg(e order by (e->>'confidence')::numeric desc nulls last) from (
          select jsonb_build_object(
            'source','vehicle_field_sources','value',fs.field_value,
            'source_type',fs.source_type,'confidence',fs.confidence_score,
            'verified',fs.is_verified,'reasoning',fs.ai_reasoning,
            'image_id',i.id,'at',fs.created_at) as e
          from public.vehicle_field_sources fs
          left join visible_images i on i.id = fs.source_image_id
          where fs.vehicle_id = p_vehicle_id and fs.field_name = p_field
            and coalesce(fs.field_value,'') <> ''
          union all
          select jsonb_build_object(
            'source','field_evidence','value',fe.proposed_value,
            'source_type',fe.source_type,'confidence',fe.source_confidence,
            'verified',(fe.status='accepted'),'reasoning',fe.extraction_context,
            'image_id',i.id,'at',fe.created_at) as e
          from public.field_evidence fe
          left join visible_images i on i.id = case
            when fe.raw_extraction_data->>'photo_id'
              ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            then (fe.raw_extraction_data->>'photo_id')::uuid end
          where fe.vehicle_id = p_vehicle_id and fe.field_name = p_field
            and coalesce(fe.proposed_value,'') <> '' and fe.status <> 'superseded' and fe.status not like 'rejected%'
        ) all_e), '[]'::jsonb),
    'observations', coalesce((
        select jsonb_agg(jsonb_build_object(
            'id',o.id,'content',left(o.content_text,400),
            'value',o.structured_data->>p_field,'confidence',o.confidence_score,
            'observed_at',o.observed_at,'kind',o.kind::text,
            'source_slug',o.source_slug,'trust',o.source_trust,'source_url',o.source_url)
            order by o.confidence_score desc nulls last)
        from readable_observations o), '[]'::jsonb),
    'image_observations', coalesce((
        select jsonb_agg(jsonb_build_object(
            'observation_id',o.id,'image_id',o.visible_image_id,
            'witness_id',o.witness_id,'witness_role',o.witness_role,
            'image_url',o.visible_image_url,'value',o.structured_data->>p_field,
            'source_slug',o.source_slug,'source_url',o.source_url,
            'extraction_method',o.extraction_method,'agent_model',o.agent_model,
            'observed_at',o.observed_at,'ingested_at',o.ingested_at,
            'confidence',o.confidence_score,
            'claim_role',o.structured_data->>'claim_role',
            'image_region',o.structured_data->'image_region',
            'reference',o.structured_data->'reference',
            'source_family',o.structured_data->>'source_family',
            'visual_relation',o.structured_data->>'visual_relation',
            'limitation',coalesce(o.structured_data->>'limitation',o.extraction_metadata->>'limitation'),
            'is_inferred',coalesce(o.structured_data->'is_inferred',o.extraction_metadata->'is_inferred'))
            order by o.confidence_score desc nulls last, o.ingested_at desc, o.id)
        from image_observations o), '[]'::jsonb)
  ) end
$function$;

COMMENT ON FUNCTION public.get_field_provenance(uuid, text) IS
'Read-only provenance at vehicle × field grain, gated to public vehicle or owner. Retains legacy iOS fields. image_observations reads typed derived witness edges first, with validated JSON image_id fallback only for observations without derived edges; every image must remain visible and keyed to this same vehicle. observed_at is observation/review event time, ingested_at is ingest time; neither asserts capture time. Confidence is stored testimony confidence, not calibrated visual proof. Legacy JSON references remain compatibility-only; new insert projection enforces typed image links. Witness role derived names the projection and does not establish visual correctness or independent witnesses.';

NOTIFY pgrst, 'reload schema';
