-- Cron accountability, part 1 of 5 — the four per-minute derived-field drains become ONE 5-minute job.
-- Session cb179857 / jobs-rebuild, 2026-09-27. Skylar: "those are your scheduled jobs that you arent
-- keeping track of". Ledger: docs/ledger/CRON_LEDGER.md (generated by `npm run ledger:facts`).
--
-- WHAT WAS WRONG (measured 2026-09-27 00:00–00:40Z):
--  * Jobs 474/475/476/477 each opened a connection every minute — 5,760 starts a day — to drain queues
--    that held 1, 8, 0 and 0 rows. On the current 411 MiB box a start costs a backend + catalog load;
--    postgres_logs 16:00–00:04Z: 1,889 cron starts, 950 "job startup timeout". Runs that did start died
--    at the postgres role's 10 s statement_timeout inside the vehicles trigger chain (38 triggers fire on
--    a single-row update: search_vector recompute, vehicle_status_metadata upsert, field-evidence
--    collection, completion enqueue, ...).
--  * Two per-minute drains updating the same vehicles row deadlocked: vehicle_metric_recompute_queue row
--    26f90c1b… carries last_error "deadlock detected" (2026-09-26 20:49Z). One sequential drain cannot
--    deadlock with itself.
--  * A cancelled outer statement rolls back the dequeue AND the retry accounting (the 2026-07-27 lesson,
--    20260727200000). So this function keeps a wall-clock budget and returns normally before the job's
--    own statement_timeout; its progress always commits.
--
-- DESIGN: one job, `drain-vehicle-derived-queues`, every 5 minutes (288 starts/day instead of 5,760).
-- Its command is "SET statement_timeout = '55s'; SELECT public.drain_vehicle_derived_queues();" —
-- PostgreSQL 13+ applies statement_timeout per statement of a multi-statement job string, so the job
-- carries its own budget whatever the role default is. The existing drain functions are called
-- unchanged; batch sizes are upper bounds, the 45 s wall-clock budget governs. The value queue (476) is
-- excluded until bat-to-db has corrected sale data (lead's order 2026-09-27): switch the job command to
-- p_include_value := true when cleared.
--
-- Created PAUSED. Re-enable one job at a time after the health gate (CRON_LEDGER.md). Jobs 474–477 stay
-- paused as superseded; unscheduling them is Skylar's call.
-- SCHEMA_LAW: no new table. One function, one cron row.

CREATE OR REPLACE FUNCTION public.drain_vehicle_derived_queues(
  p_include_value boolean DEFAULT false,
  p_budget_seconds integer DEFAULT 45
)
RETURNS TABLE(queue text, processed integer, errored integer, skipped boolean)
LANGUAGE plpgsql
AS $function$
DECLARE
  v_deadline timestamptz := clock_timestamp() + make_interval(secs => p_budget_seconds);
  v_p    integer;
  v_e    integer;
  v_name text;
BEGIN
  -- The drains' writebacks must not re-enqueue completion recomputes (update_vehicle_completion reads this).
  PERFORM set_config('app.skip_completion_enqueue', '1', true);

  FOREACH v_name IN ARRAY ARRAY['metric', 'completion', 'stats', 'value'] LOOP
    queue := v_name; processed := 0; errored := 0; skipped := false;

    IF v_name = 'value' AND NOT p_include_value THEN
      skipped := true;                       -- off until the sale data is clean
    ELSIF clock_timestamp() >= v_deadline THEN
      skipped := true;                       -- budget spent; the next run continues
    ELSE
      BEGIN
        v_p := NULL; v_e := NULL;
        CASE v_name
          WHEN 'metric'     THEN SELECT d.processed, d.errored INTO v_p, v_e FROM public.drain_vehicle_metric_queue(100) d;
          WHEN 'completion' THEN SELECT d.processed, d.errored INTO v_p, v_e FROM public.drain_vehicle_completion_queue(50) d;
          WHEN 'stats'      THEN SELECT d.processed, d.errored INTO v_p, v_e FROM public.drain_vehicle_stats_queue(50) d;
          WHEN 'value'      THEN SELECT d.processed, d.errored INTO v_p, v_e FROM public.drain_vehicle_value_queue(100) d;
        END CASE;
        processed := coalesce(v_p, 0);
        errored   := coalesce(v_e, 0);
      EXCEPTION
        WHEN query_canceled THEN
          RAISE;                             -- the job's own budget fired; fail loudly, do not swallow
        WHEN OTHERS THEN
          errored := -1;                     -- whole-drain failure (distinct from per-vehicle errors)
          RAISE WARNING 'drain_vehicle_%_queue failed: %', v_name, SQLERRM;
      END;
    END IF;

    RETURN NEXT;
  END LOOP;
END;
$function$;

COMMENT ON FUNCTION public.drain_vehicle_derived_queues(boolean, integer) IS
  'One 5-minute pass over the metric, completion, stats (and, when p_include_value, value) recompute queues with a wall-clock budget. Replaces per-minute crons 474-477. Cron: drain-vehicle-derived-queues. 2026-09-27.';

REVOKE ALL ON FUNCTION public.drain_vehicle_derived_queues(boolean, integer) FROM PUBLIC, anon, authenticated;

DO $do$
DECLARE
  v_id bigint;
  v_cmd text := $cmd$SET statement_timeout = '55s'; SELECT public.drain_vehicle_derived_queues(p_include_value := false);$cmd$;
BEGIN
  SELECT jobid INTO v_id FROM cron.job WHERE jobname = 'drain-vehicle-derived-queues';
  IF v_id IS NULL THEN
    v_id := cron.schedule('drain-vehicle-derived-queues', '*/5 * * * *', v_cmd);
    -- Created paused: nothing comes back on before the health gate holds.
    PERFORM cron.alter_job(job_id := v_id, active := false);
  ELSE
    PERFORM cron.alter_job(job_id := v_id, schedule := '*/5 * * * *', command := v_cmd);
  END IF;
END
$do$;
