-- Describe vehicle_images: the 103 columns with no COMMENT ON COLUMN (60 of 163 described before, catalog count on
-- prod, 2026-10-06), 16 corrected column comments and one corrected fact in the table comment. Comments only.
-- Describe stage of the repair loop (docs/ledger/theory/data-machine-cases.md section 12; data-machine.md
-- "the database describes itself"). vehicle_images was the top row of v_residual by rows x gaps (52.1M rows).
--
-- METHOD (read 2026-10-06 UTC):
--   Columns, types, defaults, constraints, indexes, policies and existing comments from pg_attribute, pg_constraint,
--   pg_index, pg_policy and pg_description. Writers from code at origin/main 367baf705 (supabase/functions,
--   supabase/migrations, scripts, nuke_frontend/src, apps, yono), git history for deleted writers, the 27 triggers on
--   vehicle_images, the body of every live public SQL function that names the table (238), pg_cron and
--   pipeline_registry (19 vehicle_images rows; 10 of them own a column described here).
--   "Filled" means non-NULL and, for text, non-blank; booleans count true; json and arrays count non-empty.
-- LIMITS:
--   Two populations, because the table is 98% listing links and uploaded photos vanish in a table sample:
--   (1) The table: one block sample, TABLESAMPLE SYSTEM (0.05) REPEATABLE (20261006), 25,853 of about 52.1M rows,
--       cross-checked against ANALYZE statistics (pg_stats, 300,000-row sample, autoanalyze 2026-10-01 01:57Z).
--       Block sampling clusters rows of similar age, so small table percentages are rough.
--   (2) Rows with a user_id: all 30,315 of them (created 2025-09-07 .. 2026-09-28), read through the user_id index.
--       These are the uploaded photos; most columns that read near 0% on the table live here.
--   No full-table scan was run (49 GB heap; the read API stops a statement at 10 s).
--   Writer attribution is from code and from row stamps (source, vision_model_version, ai_scan_metadata keys).
--   Deleted writers are named from git history; otherwise the comment says the writer is not established.
--   Quoted values are categorical codes only: no names, contacts, places, coordinates, paths or free text.
-- CHANGED EXISTING COMMENTS (each contradicted by code or data):
--   position: extract-bat-core does write it (insert-time gallery index, since 2026-01-10).
--   source: the value list omitted bat_import (90% of rows) and listed values ANALYZE statistics never see.
--   angle, angle_source, angle_confidence: named yono-classify, which never writes this table; value lists did not
--     match stored values; angle_confidence is empty.
--   ai_suggestions, vehicle_vin, vehicle_confidence: named writers that do not write them; all three are empty.
--   stale: photo-pipeline-orchestrator never clears it; two BYOK scripts set and clear it.
--   analysis_history: a JSON object holding arrays, not an array.
--   device_fingerprint: a dash-joined Make-Model-Lens-Software string, not an MD5.
--   zone_source, fabrication_stage: most stored values were missing from the listed values.
--   ai_processing_status, image_medium: CHECK values in use were missing (skipped is on 17% of rows).
--   file_hash: on BaT link rows it is not a hash of the file bytes.
--   Table comment: taken_at is the import time, not a capture time, on BaT link rows written 2026-01-13 .. 2026-09-27.

BEGIN;
SET LOCAL statement_timeout = '60s';
SET LOCAL lock_timeout = '5s';

COMMENT ON TABLE public.vehicle_images IS
'CANONICAL for photo (40 tables key to it; every image writer lands here). One row per image attached to, or awaiting attribution to, a vehicle (grain: one image file reference); 52M rows, 40 tables key to it. Event time = taken_at: the capture time on uploaded photos (EXIF, 2017 .. 2026-09 on sampled rows); on BaT link rows extract-bat-core wrote from 2026-01-13 to 2026-09-27 it is the import time (equal to created_at), and other listing rows leave it NULL. Ingest time = created_at. Writers: extractors (extract-bat-core and others store listing images as URLs), user upload, Apple Photos sync, and analysis functions that fill the analysis columns; pipeline_registry owners photo-pipeline-orchestrator, photo-sync-orchestrator, check-image-vehicle-match, yono-analyze, yono-classify. source says where the image came from.';

-- ── Identity, ownership and clocks ──────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.id IS
'Surrogate key of the image row. Unit: none (uuid). Source: gen_random_uuid() default. Referenced by 40 foreign keys from 40 tables (2026-10-06), one of them this table (superseded_by). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.vehicle_id IS
'Vehicle the image is attributed to, FK to vehicles.id (NOT VALID, ON DELETE RESTRICT). NULL means not yet attributed: 38.7% of the 30,315 rows with a user_id and 0.2% of the table (2026-10-06 block sample). Set at insert by the writing extractor or uploader. Changed later by: derive_vehicle_image_attribution() (cron derive-vehicle-image-attribution every 5 minutes plus a nightly sweep; promotes the strongest active image_observations subject claim at confidence 0.85 or more, human claims first), attribute_testimony() (first attribution of an unattributed image), relink_testimony() and resort_image() (moves that record merged_from_vehicle_id), merge_into_primary() (vehicle merges), accept_vehicle_suggestion() and bulk_link_photos_to_vehicle() (personal photo library), photo-pipeline-orchestrator and the iOS AttributionEngine (VIN match). reattribute_observation() copies the image to a new row instead and supersedes this one. Triggers keep the vehicle image count, has_photos flag and primary image in step. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.user_id IS
'Account that uploaded the image, FK to auth.users.id (ON DELETE CASCADE: deleting the account deletes its rows). NULL for automated listing imports (allowed since migration 20260124120000). Set by the uploader (web app, iOS capture app, photo sync and intake scripts, ingest_image_identity_first()); when NULL at insert, trigger trg_vehicle_images_default_attribution fills it from the first of documented_by_user_id, submitted_by, imported_by and ghost_user_id. RLS lets an account read its own rows by it. Filled on 30,315 rows on 2026-10-06 (created 2025-09-07 .. 2026-09-28), 0.05% of the table (ANALYZE statistics, 2 distinct accounts). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.image_url IS
'URL the image is shown from. On listing rows (is_external true, 98.4% of the table) it is the source platform link, not a stored copy: bringatrailer.com on 90% of the 2026-10-06 block sample, then cloudinary, carsandbids, Barrett-Jackson, Mecum, Craigslist and other CDNs. On rows with a user_id it is the public Supabase Storage URL of the uploaded object (29,965 of 30,315), or the empty string: the iOS capture app writes empty for metadata-only rows whose pixels its on-device gate kept on the phone (271 rows, created 2026-06-19 .. 2026-06-21). NOT NULL; CHECK vehicle_images_url_scheme_check (NOT VALID) allows empty, http(s) and data:image values. Source: every image writer at insert; extract-bat-core normalizes BaT URLs. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.image_type IS
'Image type label, mostly unused. general (the default) on 99.98% of the table (ANALYZE statistics, 2026-10-01). Other values: gallery and exterior from scripts/ingest-collective-auto-full.js; scene types (undercarriage, interior, exterior, interior_teardown, parts_on_bench and others) on 25 rows from scripts/daily-receipt/process-photo.mjs and process-photo-cascade.mjs (2026-05-23 and 2026-05-29). ingest_image_identity_first() passes a payload value or general. No CHECK. Classification lives in category, angle, vehicle_zone and ai_scan_metadata. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.category IS
'Coarse subject category, free text with no CHECK or shared vocabulary. general (the default) on 99.7% of the table (ANALYZE statistics, 2026-10-01). Other values by writer: exterior, interior, engine, undercarriage (extract_ai_analysis_to_fields() from the appraiser output, listing extractors); exterior_body, engine_mechanical, work_progress, documentation (2025 analysis era, the image_category taxonomy); vehicle_exterior, vehicle_interior, engine_bay, not_automotive, shop_environment (photo_auto_sync rows of 2026-02 .. 2026-04, writer not established); work (image-intake); documentation (auto-sort-photos, forensic-deal-jacket); reference (ingest_image_identity_first() default for images the uploader did not take); scene types (daily-receipt scripts). Some rows hold pipe-joined lists. 50 distinct values on the 30,315 rows with a user_id (2026-10-06). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.caption IS
'Short free-text description of the image: a model-written one-liner or a person-typed caption; no column records which. Writers: scripts/vision-loop-daemon.mjs (local Ollama qwen2.5vl), image-intake (model description), scripts/classify-work-photos.py, scripts/daily-receipt/process-photo.mjs and process-photo-cascade.mjs, the web app image editors, mcp-connector and imessage-router. Filled on 6.3% of the 30,315 rows with a user_id (rows created 2025-09-25 .. 2026-07-02) and about 0.006% of the table (ANALYZE statistics, 2026-10-01). Up to 500 characters. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.created_at IS
'When the row was inserted. Unit: timestamptz (UTC). Source: now() default; extract-bat-core and some scripts pass their own read time. Rows with a user_id range 2025-09-07 .. 2026-09-28 (2026-10-06). Grain: one image. Clock: ingest.';
COMMENT ON COLUMN public.vehicle_images.updated_at IS
'When the row last changed. Unit: timestamptz (UTC). Source: trigger update_vehicle_images_updated_at sets now() on every UPDATE of any column (including provenance merges into exif_data, analysis writes and attribution moves); many writers also pass it. photo-pipeline-orchestrator uses it as a compare-and-swap token, and reset_stuck_photo_pipeline_images() uses it to find stuck rows. Not a change log. Grain: one image. Clock: ingest (last write).';
COMMENT ON COLUMN public.vehicle_images.uploaded_at IS
'Upload time, a near-duplicate of created_at: within 5 seconds of created_at on every sampled row (2026-10-06 block sample and all rows with a user_id). Source: now() default since migration 20251119030000, which backfilled it from created_at; scripts/nuke-photo-sync.py and scripts/photo-sync-poc.py pass their own clock. The organization page shows it when taken_at is NULL. Unit: timestamptz (UTC). Grain: one image. Clock: ingest.';

-- ── Capture metadata ────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.exif_data IS
'Per-image metadata as JSON; the content depends on the writer. On uploaded photos: camera metadata from the uploader (keys such as camera_make, camera_model, DateTimeOriginal, iso, lens_model, location, labels, score, synced_by, uuid; from scripts/iphoto-intake.mjs, the iOS capture app, the web upload, ingest_image_identity_first() and derive-image-exif). On listing rows it is not EXIF but import provenance: extract-bat-core writes original_url, source_url, discovery_url, imported_from, imported_at, listing_urls and listing_positions (the per-listing gallery index) and merges later listings in place; backfill-images writes original_url, import_source, import_index and vehicle_year, vehicle_make, vehicle_model. Triggers derive device_fingerprint and device_attributions rows from its Make, Model, LensModel and Software. Filled on 53% of the table (2026-10-06 block sample) and 90% of the 30,315 rows with a user_id. Unit: none. Grain: one image. Clock: n/a (capture fields carry the camera clock).';
COMMENT ON COLUMN public.vehicle_images.timeline_event_id IS
'Timeline event the image is grouped into (timeline_events.id; no FK). Set at insert by trigger trg_auto_group_photos (auto_group_photos_into_events) whenever taken_at is set: it links the image to the vehicle timeline_events row of that calendar day, or creates a pending_analysis photo_upload event. Because extract-bat-core stamped its import time as taken_at until 2026-09-27, BaT link rows were grouped into per-import-day events (4,528 of the 25,853 rows in the 2026-10-06 block sample). auto-create-bundle-events, create-work-session-from-evidence and backfill_timeline_event_for_image() fill it where NULL. Filled on 18% of the table and 84% of the 30,315 rows with a user_id. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.image_context IS
'Free-text tag for the context the image came from. facebook_marketplace from the FB Marketplace scripts (scripts/extract-images.ts and scripts/marketplace-monitor/bulk-extract*.ts, which also delete rows by it); one row with a user_id holds listing (2026-07-02). About 0.004% of the table (ANALYZE statistics, 2026-10-01). Added by migration 20250830_vehicle_events_extension. scripts/vision-gate-classify.mjs reads it as caption-like evidence. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.file_name IS
'Original file name of the uploaded photo (camera or library name). Twin of filename: 5,408 rows carry both and the two differ on all 5,408, so neither is canonical. Writers: scripts/iphoto-intake.mjs, the iOS capture app, scripts/drop-folder-ingest.mjs, scripts/bulk-photo-upload.mjs, scripts/archive-intake.mjs, the daily-receipt scripts, mcp-connector and the web upload; ingest_image_identity_first() keeps the name on image_identities.original_filename instead. Filled on 74.7% of the 30,315 rows with a user_id (rows created 2025-09-07 .. 2026-06-24) and 0.14% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.taken_at IS
'When the photo was taken, as its writer understood it. On uploaded photos: the camera EXIF DateTimeOriginal (scripts/iphoto-intake.mjs, ingest_image_identity_first(); derive-image-exif fills NULLs from the stored file). Older iOS capture builds stored the Photos library add date instead, which the app reconcile (SupabaseService.reconcilePhoto) repairs from EXIF. NOT a capture time on listing rows: extract-bat-core stamped its import time (equal to created_at) on BaT link rows from 2026-01-13 (3f9667c22) until 2026-09-27 (c40679fa2), and backfill-images writes the listing date or the run date. Filled on 99.6% of the 30,315 rows with a user_id (1981-01-20 .. 2026-09-26) and 23% of the table, 97% of which are BaT import times (2026-10-06 block sample). Drives trigger trg_auto_group_photos. Unit: timestamptz. Grain: one image. Clock: event (capture) on uploaded photos; ingest on BaT link rows.';
COMMENT ON COLUMN public.vehicle_images.latitude IS
'Latitude where the photo was taken. Owner-private location. Unit: decimal degrees (WGS84 implied). Source: GPS from EXIF or the Photos library at upload (scripts/iphoto-intake.mjs, the iOS capture app and its reconcile, image-intake, ingest_image_identity_first(), scripts/backfill-image-gps-and-orgs.js). Trigger trg_auto_tag_org_from_gps links the vehicle to a business within 500 m as a work_location in organization_vehicles. Filled on 76.7% of the 30,315 rows with a user_id and 0.08% of the table (2026-10-06). Grain: one image. Clock: n/a (location at capture time).';
COMMENT ON COLUMN public.vehicle_images.longitude IS
'Longitude where the photo was taken; pairs with latitude. Owner-private location. Unit: decimal degrees, negative west (WGS84 implied). Source: the same writers as latitude. Filled on 76.7% of the 30,315 rows with a user_id and 0.08% of the table (2026-10-06). Grain: one image. Clock: n/a (location at capture time).';
COMMENT ON COLUMN public.vehicle_images.location_name IS
'Place label for where the photo was taken. Owner-private. Two shapes on the 11,635 rows with a user_id that carry it (2026-10-06): a lowercase known-place key (8,564 rows; writer not established) or a reverse-geocoded address line (3,071 rows; scripts/iphoto-intake.mjs from the Photos library place, scripts/backfill-image-gps-and-orgs.js). Not keyed to a place or organization table. Filled on 38.4% of rows with a user_id (rows created 2025-10-16 .. 2026-06-11) and 0.04% of the table. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.location_confidence IS
'UNUSED: intended confidence 0-1 of the photo location, for EXIF validation (migration 20260201_ownership_hierarchy_fix). No writer in the repo or among live SQL functions; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: ratio 0-1. Grain: one image. Clock: n/a.';

-- ── Privacy and moderation ──────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.is_sensitive IS
'Privacy flag: true hides the image from everyone but its owner. The public read policy (Users can view images for public vehicles) and get_vehicle_profile_data() skip sensitive rows; scripts/vision-gate-classify.mjs turns it into vision_gate_status rejected_personal. Writers: set_image_sensitivity() (the sanctioned privacy writer, migration 20260928213000; records who, when and why in redacted_by, redacted_at and redaction_reason), detect-sensitive-document (titles and registrations; also sets is_document), the web upload (false). NOT NULL, default false. True on 480 of the 30,315 rows with a user_id (2026-10-06; 476 of them set 2026-09-28 .. 2026-09-29) and about 4 in 300,000 rows of the table (ANALYZE statistics). Unit: boolean. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.sensitive_type IS
'Why the image is sensitive: document (313 rows), personal (163) and title (4) on rows with a user_id (2026-10-06). Set with is_sensitive by set_image_sensitivity() (NULL again when the flag is cleared) and by detect-sensitive-document (its document type). The 2025 design listed face, title, license_plate and personal_info; only title is stored. No CHECK. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.safe_preview_url IS
'UNUSED: intended URL of a redacted or blurred preview shown in place of a sensitive image (migration 20251119000003_public_content_visibility). No writer; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). scripts/dhash-backfill.mjs and mcp-connector read it as a URL fallback. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.approved_by IS
'Account whose upload was auto-approved, FK to auth.users.id (ON DELETE SET NULL). Set at insert by trigger trg_auto_approve_vehicle_images (apply_auto_approval_for_image) to the acting account when auto_approve_vehicle_content(vehicle, actor) returns auto_approved, together with approved_at. Importers that insert approval_status auto_approved without an acting account leave it NULL. No code writes a human approval here. Filled on 3,355 of the 30,315 rows with a user_id (exactly their auto_approved rows) and about 0.008% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.approved_at IS
'When trigger trg_auto_approve_vehicle_images auto-approved the row (insert time), set with approved_by. 2025-11-22 .. 2026-07-02 on the 3,355 rows with a user_id that carry it (2026-10-06). Unit: timestamptz (UTC). Grain: one image. Clock: ingest (approval at insert).';
COMMENT ON COLUMN public.vehicle_images.pending_submission_id IS
'UNUSED: intended link to the contribution_submissions row awaiting review for this image; migration 20251103000001_contribution_verification_system declared a FK that prod does not have. No writer; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.submitted_by IS
'Account that submitted the image, FK to profiles.id. Set at insert by trigger trg_auto_approve_vehicle_images to the first of submitted_by, user_id and auth.uid(); it stays NULL when a service-role writer names no account before trg_vehicle_images_default_attribution fills user_id, so many uploads lack it. Filled on 51.3% of the 30,315 rows with a user_id and 0.04% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.redaction_level IS
'How much of the image is masked, enum content_redaction_level: none, details_hidden, full_blur. NOT NULL, default none; none on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06): no code sets another value, and the 2026-09-28 privacy containment used is_sensitive instead. Listing extractors write none explicitly; the public auction gallery eligibility check and photo-pipeline-orchestrator classifierAssay require none. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.redacted_by IS
'Account recorded by set_image_sensitivity() as the actor of the last privacy-flag change, FK to profiles.id. It records the flag decision; the pixels are not altered. 476 rows with a user_id, all set 2026-09-28 .. 2026-09-29 (2026-10-06). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.redacted_at IS
'When set_image_sensitivity() last changed the privacy flag (now()). 476 rows with a user_id, 2026-09-28 21:18 .. 2026-09-29 05:27 UTC (2026-10-06). Unit: timestamptz (UTC). Grain: one image. Clock: ingest (decision time).';
COMMENT ON COLUMN public.vehicle_images.redaction_reason IS
'Free-text reason passed to set_image_sensitivity() (required) for the last privacy-flag change, for example the on-device gate verdict or the 2026-09-28 containment. 476 rows with a user_id, 4 distinct reasons (2026-10-06). Unit: none. Grain: one image. Clock: n/a.';

-- ── Work-photo tags (2025-09 web importer taxonomy; most were added before the 2025-10-12 history reset) ──────

COMMENT ON COLUMN public.vehicle_images.process_stage IS
'Build stage of the work shown, from file-name hints. Values: discovery, mechanical, undercarriage, wiring, paint_prep, disassembly, paint_stage1 (145 rows with a user_id, all created 2025-09-25); the original tagger also defined metalwork, bodywork, paint_stage2, reassembly, final and upholstery. Writers: the web app (AddEventWizard.tsx with default discovery, unifiedImageImportService.ts), originally the 2025-09 web importer VehicleImageImport.tsx (removed). About 0.001% of the table (ANALYZE statistics, 2026-10-01). fabrication_stage is the current stage column. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.workflow_role IS
'UNUSED: role of the photo in a work job (before, after, issue, receipt, parts, during), set from file-name hints by the 2025-09 web importer VehicleImageImport.tsx (removed). No current writer; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). The image viewer (useImageViewerState.ts) filters on it. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.area IS
'Vehicle area or system the work photo shows, free text. Values on the 1,306 rows with a user_id that carry it (2026-10-06): underbody, exhaust, front, interior, other, wheels_brakes, side, engine, rear, suspension, general and others (39 distinct). Writers: scripts/vision-loop-daemon.mjs (local Ollama qwen2.5vl), scripts/classify-work-photos.py, scripts/daily-receipt/process-photo.mjs and process-photo-cascade.mjs; rows created 2026-03-20 .. 2026-05-29. The 2025-09 web importer set it from file-name hints. vehicle_zone is the controlled zone column. About 0.001% of the table (ANALYZE statistics). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.part IS
'Parts visible in the work photo, as a comma-separated free-text list of up to 200 characters (873 distinct values on 924 rows with a user_id, 2026-10-06). Writers: scripts/vision-loop-daemon.mjs (its parts_visible), scripts/daily-receipt/process-photo.mjs and process-photo-cascade.mjs; rows created 2026-03-20 .. 2026-05-29. Not keyed to a parts catalog. About 0.001% of the table (ANALYZE statistics). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.damage_type IS
'UNUSED: kind of damage shown (rust, dent, crack or leak), set from file-name hints by the 2025-09 web importer VehicleImageImport.tsx (removed). No current writer; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). The web valuation engine (valuationEngine.ts) reads it with damage_flags, which is the populated damage column. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.operation IS
'Work activity shown, free text (54 distinct values on 1,305 rows with a user_id, 2026-10-06): static, in_progress_work, disassembly, welding, documentation, condition_assessment, fabrication, progress and others. Writers: scripts/vision-loop-daemon.mjs (its action field), scripts/classify-work-photos.py, scripts/daily-receipt/process-photo.mjs and process-photo-cascade.mjs; rows created 2026-03-20 .. 2026-05-29. About 0.001% of the table (ANALYZE statistics). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.materials IS
'UNUSED: materials visible (primer, 2k, basecoat, clear, undercoat, sound_deadener, heat_shrink), set from file-name hints by the 2025-09 web importer VehicleImageImport.tsx (removed). No current writer; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: none (text array). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.labels IS
'Short labels for the image as a text array; the vocabulary depends on the writer. scene:, phase: and intent: prefixed tags plus component names from scripts/daily-receipt/analyze-capture-photos.mjs (184 capture-app rows, 2026-06-12 .. 2026-06-13); AWS Rekognition label names copied by extract_ai_analysis_to_fields() from ai_scan_metadata.rekognition; tags from scripts/work-photos-intake.mjs. Apple Photos labels live in apple_ml_labels instead. Filled on 274 of the 30,315 rows with a user_id and 0.03% of the table (2026-10-06). Unit: none (text array). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.task_id IS
'Unknown meaning: no writer in the repo history or among live SQL functions, no FK, and no rows (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Added with the work-photo tag columns before the 2025-10-12 history reset; the task table it was meant to key is not recorded. Unit: none (uuid). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.event_id IS
'Unknown meaning: no writer, no FK and no rows (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Added with the work-photo tag columns before the 2025-10-12 history reset. The populated event link is timeline_event_id. Unit: none (uuid). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.perspective IS
'UNUSED: lens perspective from the EXIF focal length (wide at 28 mm or less, tele at 61 mm or more, else normal), set by the 2025-09 web importer VehicleImageImport.tsx (removed). No current writer; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). camera_pose holds the current structured viewpoint. Unit: none. Grain: one image. Clock: n/a.';

-- ── Resized copies ──────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.variants IS
'URLs of resized copies as JSON: full, large, medium and thumbnail keys pointing at Supabase Storage objects. Written by the web upload (nuke_frontend imageUploadService.ts) on 5,773 of the 30,315 rows with a user_id (created 2025-09-25 .. 2025-12-07); later uploaders do not write it. Default {}; empty on 99.99% of the table (ANALYZE statistics 2026-10-01). thumbnail_url, medium_url and large_url hold the same idea as columns and are nearly empty. Unit: none. Grain: one image. Clock: n/a.';

-- ── Analysis outputs and receipts ───────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.ai_scan_metadata IS
'Analysis receipts and outputs as one JSON object, keyed by writer. Keys seen (2026-10-06): photo-pipeline-orchestrator writes classification, pipeline_version, route_result, processed_at, duration_ms, classifier_failed, deep_byok_enqueued and photo_pipeline (its processing receipt, written by compare-and-swap on updated_at); scripts/deep-image-analysis-byok.mjs writes byok_deep_analysis; extract-bat-core writes image_intake on new BaT links (a declaration that the link was not analyzed, since 2026-09-27); ingest_image_identity_first() writes identity_first; appraiser, tier_1_analysis, scanned_at and rekognition come from deleted analysis functions; on_device_vision comes from the iOS app. scripts/vision-loop-daemon.mjs replaces the whole object when it writes. Default {}; non-empty on 27% of the table (block sample) and 94% of the 30,315 rows with a user_id. Unit: none. Grain: one image. Clock: derived (each key carries its own run time where it has one).';
COMMENT ON COLUMN public.vehicle_images.ai_last_scanned IS
'When an analysis pass last scanned the image. Writers: scripts/vision-loop-daemon.mjs, forensic-deal-jacket (with its ai_extractions entry), scripts/backfill-all-images.js and the deleted analyze-image functions; update_image_ai_metadata() also sets it but is attached to no trigger and its source table no longer exists. 2025-09-25 .. 2026-06-24 on the 4,541 rows with a user_id that carry it (15%, 2026-10-06); 0.02% of the table (ANALYZE statistics). Current pipelines stamp vision_analyzed_at and last_rerun_at instead. Unit: timestamptz (UTC). Grain: one image. Clock: derived (scan time).';
COMMENT ON COLUMN public.vehicle_images.ai_component_count IS
'Number of components detected in the image. Default 0, so 0 means not counted as often as none seen (0 on 99.99% of the table, ANALYZE statistics 2026-10-01). Writers: promote_image_depth_to_columns() (length of ai_scan_metadata.byok_deep_analysis.components_seen; run per vehicle or user by scripts/daily-receipt/byok-image-batch.sh); extract_ai_analysis_to_fields() fills it only when NULL, which the default prevents. 0 .. 16 on rows with a user_id (2026-10-06). Unit: count. Grain: one image. Clock: derived (as of the last promotion).';
COMMENT ON COLUMN public.vehicle_images.ai_avg_confidence IS
'MIXED, despite its name: on most filled rows it is not a confidence. extract_ai_analysis_to_fields() stores the appraiser condition_score divided by 10 (7,798 of the 10,188 rows with a user_id that carry it equal that ratio, 2026-10-06). Other writers: promote_image_depth_to_columns() (mean confidence of byok_deep_analysis.components_seen) and scripts/vision-loop-daemon.mjs (its classifier confidence); update_image_ai_metadata() is detached. 0.00 .. 1.00. Filled on 33.6% of rows with a user_id and 0.14% of the table (ANALYZE statistics). Unit: ratio 0-1. Grain: one image. Clock: derived.';
COMMENT ON COLUMN public.vehicle_images.image_category IS
'Subject category from the 2025 image analysis era: exterior_body, interior, engine_mechanical, undercarriage, documentation, work_progress, trunk_storage, wheels_tires, detail_shot and a few pipe-joined combinations (20 distinct values on rows with a user_id, 2026-10-06). The bulk writer is not in the repo (rows created 2025-09-07 .. 2025-12-07, plus one in 2026-06); import-pcarmarket-listing writes exterior and two scripts write exterior or unknown. Filled on 27.6% of the 30,315 rows with a user_id and 0.02% of the table (ANALYZE statistics). The iOS app reads it as its vision category; category shares this taxonomy on older rows. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.context_score IS
'UNUSED: intended context-richness score for multi-model analysis (migration 20251122_add_multi_model_tracking). Default 0, and 0 on every sampled row (2026-10-06 block sample, all rows with a user_id, ANALYZE statistics). scripts/context-driven-processor.js computes such a score, but no row carries a non-zero value. Unit: points (integer). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.processing_models_used IS
'Models that analyzed the image, appended per run (de-duplicated, at most 25) by the analyze-image edge function, deleted 2026-03-07 (9ab2fd4b7). No current writer. Default empty array; non-empty on 11 rows with a user_id (created 2025-09-22 .. 2025-10-21) and about 0.003% of the table (ANALYZE statistics, 2026-10-01). Unit: none (text array). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.total_processing_cost IS
'Running total of model cost spent analyzing the image, added per run by the analyze-image edge function (deleted 2026-03-07, 9ab2fd4b7). No current writer. Default 0; non-zero on about 0.003% of the table (ANALYZE statistics, 2026-10-01), at most 0.012221 on rows with a user_id. Unit: USD (numeric(10,6)). Grain: one image. Clock: derived (total as of the last run).';
COMMENT ON COLUMN public.vehicle_images.ai_extractions IS
'Every AI extraction attempt for the image as a JSON array of entries with extracted_at, model, confidence and data. Writers: add_ai_extraction() (appends and rebuilds ai_extraction_consensus; called by scripts/organize-ai-analysis-data.js), a 2025-12-28 backfill from ai_scan_metadata.appraiser (migration 20250128000003; model gpt-4o), and forensic-deal-jacket (a forensic_deal_jacket entry). Default empty array; non-empty on 29.4% of the 30,315 rows with a user_id (created 2025-09-07 .. 2026-03-27) and 0.15% of the table (2026-10-06 block sample). Unit: none. Grain: one image. Clock: derived (each entry carries extracted_at).';
COMMENT ON COLUMN public.vehicle_images.ai_extraction_consensus IS
'Consensus per field across ai_extractions as JSON: each field (angle and category seen) maps to value, confidence and extraction_count. Rebuilt by add_ai_extraction() through build_extraction_consensus() whenever an extraction is added. Default {}; non-empty on 29.3% of the 30,315 rows with a user_id and 0.13% of the table (2026-10-06 block sample). Unit: none. Grain: one image. Clock: derived (as of the last extraction).';

-- ── Gallery order and notes ─────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.manual_priority IS
'Owner-set display priority; higher sorts first and the web gallery badges values above 0. Written only by set_image_priority(), which checks that the caller owns or edits the vehicle. Default 0, and 0 on every sampled row (2026-10-06 block sample, all rows with a user_id, ANALYZE statistics). Unit: points (integer). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.display_order IS
'Gallery order of a listing image: its index in the source gallery when the row was inserted (0 = first). Written by extract-bat-core, extract-cars-and-bids-core, extract-gooding, extract-broad-arrow, extract-hagerty-listing, extract-vehicle-data-ai, backfill-images and listing scripts; most of them write the same index to position. Not updated when a gallery is read again; extract-bat-core keeps the per-listing order in exif_data.listing_positions. Default 0; 0 on every row with a user_id; 0 .. 1,075 in the 2026-10-06 block sample. Unit: ordinal. Grain: one image. Clock: n/a (as of insert).';
COMMENT ON COLUMN public.vehicle_images.user_tags IS
'UNUSED: owner-entered tags (migration 20251123_image_sets_system). No writer; empty on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: none (text array). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.user_notes IS
'Free-text note on the image. Designed as the owner note (migration 20251123_image_sets_system); in practice it holds bracketed operator repair notes, most recording why a photo was detached from a vehicle on 2026-06-25 or 2026-07-02 (380 rows with a user_id, 8 distinct notes, 2026-10-06), written outside the repo. scripts/vision-gate-classify.mjs reads it as caption-like evidence. Unit: none. Grain: one image. Clock: n/a.';

-- ── Attribution and suggestions ─────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.organized_at IS
'When the image was filed to a vehicle from the personal photo library. Set by accept_vehicle_suggestion(), bulk_link_photos_to_vehicle() and convert_personal_album_to_vehicle() (with organization_status organized) and by Craigslist image-linking scripts; the web lightbox clears it on unlink. 2025-11-24 .. 2025-12-07 on 313 rows with a user_id (2026-10-06); none in ANALYZE statistics. The later attribution paths (derive_vehicle_image_attribution(), attribute_testimony(), the iOS app) do not set it. Unit: timestamptz (UTC). Grain: one image. Clock: event (filing time).';
COMMENT ON COLUMN public.vehicle_images.ai_detected_vehicle IS
'Vehicle a vision model saw in the image, stored as a JSON string (a year make model description), not an object. Written by check-image-vehicle-match (its detected_vehicle) and scripts/process-personal-library-images.js. 54 rows with a user_id and 0.07% of the table, mostly listing rows created 2026-01 .. 2026-07 (2026-10-06 block sample). Unit: none. Grain: one image. Clock: derived (as of the check).';
COMMENT ON COLUMN public.vehicle_images.ai_detected_angle IS
'Angle label from an AI pass, kept apart from angle. Writers: extract_ai_analysis_to_fields() (the appraiser angle or primary_label, the same values as angle), scripts/vision-loop-daemon.mjs (front, rear, side, interior, engine_bay, undercarriage, wheel, detail or document, mapped from its scene class), scripts/process-personal-library-images.js, and the deleted backfill-image-angles (Gemini angle families, removed 2026-04-06). 29 distinct values on 9,768 rows with a user_id (32.2%) and 0.15% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.ai_detected_angle_confidence IS
'MIXED, despite its name: on 8,272 of the 8,334 rows with a user_id that carry it (2026-10-06) it equals the appraiser condition_score divided by 10, written by extract_ai_analysis_to_fields(), so there it is a condition rating, not an angle confidence. scripts/process-personal-library-images.js and the deleted backfill-image-angles wrote true angle confidences. get_inventory_angle_coverage_metrics() reads it as a confidence. Filled on 27.5% of rows with a user_id and 0.13% of the table (ANALYZE statistics). Unit: ratio 0-1 (real). Grain: one image. Clock: derived.';
COMMENT ON COLUMN public.vehicle_images.suggested_vehicle_id IS
'Vehicle an automated matcher proposes for the image, pending owner confirmation (vehicles.id; no FK). Writers: photo-pipeline-orchestrator (a GPS and recent-work prior, not evidence), check-image-vehicle-match (when the image looks like another vehicle), auto-sort-photos, scripts/capture-sessions.mjs, scripts/daily-receipt/classify-unfiled-day.mjs and scripts/process-personal-library-images.js; reject_vehicle_suggestion() and resort_image() clear it and accept_vehicle_suggestion() files the image to it. Filled on 23.8% of the 30,315 rows with a user_id (1,045 created in the last 30 days) and 0.014% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.documented_by_device IS
'Device that took the photo as a free-text label (migration 20251204_comprehensive_work_order_receipt). Written only by ingest_image_identity_first() from its payload; about 1 row in 300,000 (ANALYZE statistics 2026-10-01) and none with a user_id (2026-10-06). device_fingerprint is the populated device key. scripts/vision-gate-classify.mjs reads it. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.documented_by_user_id IS
'Account that documented (photographed) the subject, as opposed to who uploaded or imported it, FK to auth.users.id. Trigger trg_vehicle_images_default_attribution sets it to the resolved actor when NULL and the image is not external; ingest_image_identity_first() sets it only for the uploader own captures; intake scripts (iphoto-intake, drop-folder-ingest, work-photos-intake, the iMessage sync, bulk-photo-upload, daily-receipt) and mcp-connector pass it. RLS lets the account read its unattributed images by it. Filled on 83.9% of the 30,315 rows with a user_id and 0.06% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.photographer_attribution IS
'UNUSED: free-text credit for who took the photo (migration 20251204_comprehensive_work_order_receipt). No writer; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). scripts/vision-gate-classify.mjs reads it. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.user_confirmed_vehicle IS
'Whether the owner confirmed the vehicle link (migration 20251206_user_override_columns: user decisions win over automation). Default false. True on one row, set 2026-06-24 with user_confirmed_vehicle_by and user_confirmed_vehicle_at; that writer is not in the repo. The 2026-06-14 version of attribute_testimony() wrote false explicitly; the live version does not touch it. Unit: boolean. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.user_confirmed_vehicle_by IS
'Account that confirmed the vehicle link (no FK). One row (2026-06-24, as of 2026-10-06); the writer is not in the repo. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.user_confirmed_vehicle_at IS
'When the owner confirmed the vehicle link. One row, 2026-06-24 (as of 2026-10-06); the writer is not in the repo. Unit: timestamptz (UTC). Grain: one image. Clock: event (confirmation time).';
COMMENT ON COLUMN public.vehicle_images.auto_suggested_vehicle_id IS
'Vehicle an automated attribution proposed (vehicles.id; no FK), kept beside vehicle_id so the guess stays auditable. Written by the iOS AttributionEngine (a VIN match also promotes vehicle_id; session inheritance only suggests) and by the 2026-06-14 version of attribute_testimony(). 21 rows with a user_id (capture-app rows created 2026-06-13 .. 2026-06-14) and about 2 in 300,000 rows of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.auto_suggestion_confidence IS
'Confidence 0-1 of the automated vehicle suggestion. Written with auto_suggested_vehicle_id by the iOS AttributionEngine, and with suggested_vehicle_id by check-image-vehicle-match and scripts/daily-receipt/classify-unfiled-day.mjs. 0.65 .. 1 on 41 rows with a user_id (2026-10-06). Unit: ratio 0-1 (real). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.auto_suggestion_reasons IS
'Reasons behind the automated vehicle suggestion as a text array (for example a VIN match, a session inheritance or a day-classifier evidence line). Same writers as auto_suggestion_confidence. 41 rows with a user_id (2026-10-06). Unit: none (text array). Grain: one image. Clock: n/a.';

-- ── Pose, detection and vehicle denormalization (migration 20251207_image_structured_metadata, 2025-12-08) ─────

COMMENT ON COLUMN public.vehicle_images.yaw_deg IS
'Camera yaw around the vehicle, coarse (0, 90, 180 and 270 observed). Reserved for the pose stage by the extraction contract (docs/library/technical/engineering-manual/19-extraction-contract.md); the only writer in the repo history is backfill-image-angles (a Gemini angle backfill run from the admin page, 2025-11-21 .. deleted 2026-04-06). 52 rows with a user_id (created 2025-09-08 .. 2025-11-23) and none in ANALYZE statistics (2026-10-06). Unit: degrees. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.yaw_confidence IS
'Confidence 0-1 of yaw_deg. Reserved for the pose stage; the only writer in the repo history was backfill-image-angles (deleted 2026-04-06). NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: ratio 0-1. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.bbox IS
'Reserved: bounding box of the vehicle in the frame as JSON. No row carries it (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06): the writers in the repo put boxes in image_observations.bbox (scripts/daily-receipt/process-photo-cascade.mjs) and inside components entries. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.doc_flag IS
'Whether an AI pass judged the image a document; is_document is the maintained document flag. True on 4 rows with a user_id (created 2025-11-23, each with doc_confidence 0.9) and on no row in ANALYZE statistics (2026-10-06); the writer is not in the repo. get_service_vehicles_for_org() treats it like is_document. Unit: boolean. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.doc_confidence IS
'Confidence 0-1 of doc_flag. 0.9 on the same 4 rows (2026-10-06); the writer is not in the repo. Unit: ratio 0-1. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.components IS
'Components seen in the image as JSON, in three shapes. An array of entries with label, bbox, confidence and part_number_guess on 1,768 rows with a user_id: promote_image_depth_to_columns() copies ai_scan_metadata.byok_deep_analysis.components_seen, and scripts/daily-receipt/process-photo-cascade.mjs writes its own. An object of deal-jacket flags (needs_forensic_extraction, extraction_method, forensic_extracted_at) from scripts/process-deal-jackets.py and deal-jacket-pipeline (59 rows). An object of engine-bay findings (engine_family, fuel_system, valve_covers and others, analyzed_by xai) on 22 rows; that writer is not in the repo. Filled on 6.1% of the 30,315 rows with a user_id and about 0.006% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: derived.';
COMMENT ON COLUMN public.vehicle_images.vehicle_vin_confidence IS
'UNUSED: confidence 0-1 of vehicle_vin. No writer; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: ratio 0-1. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.vehicle_make IS
'UNUSED: make of the vehicle seen in the image. No writer and no rows (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06); backfill-images puts vehicle_make inside exif_data, not here, although the extraction contract says it fills this column. Two web components read it. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.vehicle_model IS
'UNUSED: model of the vehicle seen in the image. No writer and no rows (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06); backfill-images puts vehicle_model inside exif_data, not here. Two web components read it. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.vehicle_year IS
'UNUSED: model year of the vehicle seen in the image. No writer and no rows (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06); backfill-images puts vehicle_year inside exif_data, not here. Two web components read it. Unit: year. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.vehicle_source IS
'UNUSED: how the image vehicle link was made. The 2026-06-14 version of attribute_testimony() wrote agent_gps_temporal; the live version does not, and no row carries a value (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.last_rerun_at IS
'When a BYOK deep-analysis script last wrote its verdict for the image: scripts/deep-image-analysis-byok.mjs (together with stale and vision_model_version) and scripts/daily-receipt/analyze-capture-photos.mjs. 2026-06-02 .. 2026-08-02 on 12,514 rows with a user_id (41.3%) and 0.03% of the table (ANALYZE statistics, 2026-10-01). Unit: timestamptz (UTC). Grain: one image. Clock: derived (analysis run time).';
COMMENT ON COLUMN public.vehicle_images.tags IS
'UNUSED: tag list as JSON. Default empty array; empty on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Image tags live in image_tags and labels. Unit: none. Grain: one image. Clock: n/a.';

-- ── Vision analysis (YONO and BYOK) ─────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.condition_score IS
'Exterior condition rating 1-5 from a vision model. Writers: YONO (yono-analyze edge function, the yono/modal_batch.py worker, scripts/yono-classify-vehicle.mjs; Florence-2 heads, runs of 2026-02-28 .. 2026-04-13), scripts/deep-image-analysis.mjs, scripts/daily-receipt/process-photo-cascade.mjs and mcp-connector. vision_model_version may name a later BYOK pass that did not write this score. 1 .. 5 except one row at 92 (a 0-100 value). Filled on 30.7% of the 30,315 rows with a user_id and 0.5% of the table (2026-10-06). pipeline_registry owner: yono-analyze. Unit: points 1-5. Grain: one image. Clock: derived (as of vision_analyzed_at).';
COMMENT ON COLUMN public.vehicle_images.damage_flags IS
'Damage types a vision model detected, as a text array: rust, paint_fade, dent and others (rust most common). Writers: yono-analyze and the YONO workers, scripts/deep-image-analysis.mjs, scripts/daily-receipt/process-photo-cascade.mjs and mcp-connector. Default empty array, so empty means not analyzed or nothing found. Non-empty on 14.0% of the 30,315 rows with a user_id and 0.13% of the table (ANALYZE statistics, 2026-10-01). pipeline_registry owner: yono-analyze. Unit: none (text array). Grain: one image. Clock: derived (as of vision_analyzed_at).';
COMMENT ON COLUMN public.vehicle_images.modification_flags IS
'Modifications a vision model detected, as a text array (for example lift_kit). Writers: yono-analyze and the YONO workers, scripts/deep-image-analysis.mjs and mcp-connector. Default empty array; non-empty on 384 of the 30,315 rows with a user_id (1.3%) and about 0.001% of the table (ANALYZE statistics, 2026-10-01). pipeline_registry owner: yono-analyze. Unit: none (text array). Grain: one image. Clock: derived (as of vision_analyzed_at).';
COMMENT ON COLUMN public.vehicle_images.photo_quality_score IS
'Photo usefulness rating 1-5 from a vision model (the YONO photo_quality output). Same writers and run window as condition_score; 2 .. 5 except one row at 95 (a 0-100 value). Filled on 30.6% of the 30,315 rows with a user_id and 0.5% of the table (2026-10-06). pipeline_registry owner: yono-analyze. Unit: points 1-5. Grain: one image. Clock: derived (as of vision_analyzed_at).';
COMMENT ON COLUMN public.vehicle_images.vision_analyzed_at IS
'When a vision pass last wrote the condition, zone and flag columns (yono-analyze writes now()). 2026-02-27 .. 2026-06-24 (2026-10-06); filled on 30.6% of the 30,315 rows with a user_id and 0.5% of the table. The BYOK deep passes stamp last_rerun_at instead. pipeline_registry owner: yono-analyze. Unit: timestamptz (UTC). Grain: one image. Clock: derived (analysis run time).';
COMMENT ON COLUMN public.vehicle_images.vision_model_version IS
'Model of the last vision pass, overwritten by each pass, so it does not always name the model behind condition_score or vehicle_zone. Values on rows with a user_id (2026-10-06): claude-opus-4-8 12,285, yono_v2_florence2_finetuned 3,784, finetuned_v2 275, byok_v3_opus48 219, claude-sonnet-4-6 182 and single rows. YONO writers (yono-analyze and its workers) write finetuned_v2, zeroshot_florence2 or yono_v2_florence2_finetuned; scripts/deep-image-analysis-byok.mjs and analyze-capture-photos.mjs write the BYOK model, so 5,072 claude-opus-4-8 rows carry YONO scores from 2026-02 .. 2026-04. error marks failed runs. Filled on 55.2% of rows with a user_id and 0.5% of the table. pipeline_registry owner: yono-analyze. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.surface_coord_v IS
'Reserved: vertical coordinate of the image on the vehicle surface map, to come from the COLMAP stage (yono/VISION_ARCHITECTURE.md). yono-analyze writes NULL until then; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: surface-map units, not yet defined (numeric(8,2)). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.surface_coord_u IS
'Reserved: horizontal coordinate of the image on the vehicle surface map, to come from the COLMAP stage (yono/VISION_ARCHITECTURE.md). yono-analyze writes NULL until then; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: surface-map units, not yet defined (numeric(8,2)). Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.camera_pose IS
'Structured camera viewpoint as JSON: azimuth_deg, elevation_deg, distance_est, framing, method and exif_present (the BYOK deep-analysis format). Written by promote_image_depth_to_columns() from ai_scan_metadata.byok_deep_analysis.camera_pose, scripts/daily-receipt/process-photo-cascade.mjs and mcp-connector. Filled on 5.85% of the 30,315 rows with a user_id and about 0.006% of the table (ANALYZE statistics, 2026-10-01). Unit: degrees inside the JSON. Grain: one image. Clock: derived.';
COMMENT ON COLUMN public.vehicle_images.vehicle_zone IS
'Zone of the vehicle the image shows, from the 41-zone taxonomy in yono/VISION_ARCHITECTURE.md: ext_front_driver, ext_driver_side, detail_damage, detail_badge, mech_suspension, mech_engine_bay, ext_undercarriage, int_dashboard, panel_door_fl and others (44 distinct on rows with a user_id). Writers: yono-analyze and the YONO workers (yono/modal_batch.py, yono/scripts/run_zone_inference.py, scripts/yono-classify-vehicle.mjs, scripts/yono-batch-classify.mjs), scripts/deep-image-analysis.mjs, scripts/daily-receipt/process-photo-cascade.mjs and others; zone_source names the method. Filled on 36.3% of the 30,315 rows with a user_id and 0.7% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.zone_confidence IS
'Confidence 0-1 of vehicle_zone from the YONO zone classifier, written with it by yono-analyze and the YONO workers; NULL where the zone came from another method. 0.041 .. 0.436 on rows with a user_id (2026-10-06). Filled on 30.6% of rows with a user_id and 0.5% of the table. Unit: ratio 0-1. Grain: one image. Clock: derived (as of vision_analyzed_at).';
COMMENT ON COLUMN public.vehicle_images.yono_queued_at IS
'Reserved: when the YONO vision worker claimed the image, set by claim_yono_vision_batch() (migration 20260227010000_yono_vision_worker). The function has no scheduled caller; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: timestamptz (UTC). Grain: one image. Clock: derived (claim time).';

-- ── Video ───────────────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.duration_seconds IS
'Video length, for rows that are videos. Only scripts/archive-intake.mjs writes it (with is_video); NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: seconds. Grain: one image or video file. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.video_codec IS
'Video codec name, for rows that are videos. Only scripts/archive-intake.mjs writes it; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: none. Grain: one image or video file. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.video_resolution IS
'Video frame size as text, for rows that are videos. Only scripts/archive-intake.mjs writes it; NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Unit: pixels, as written. Grain: one image or video file. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.is_video IS
'Whether the row is a video file rather than a photo. Default false; false on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). Only scripts/archive-intake.mjs sets it true. Unit: boolean. Grain: one image or video file. Clock: n/a.';

-- ── Lineage ─────────────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images.work_session_id IS
'Work session the image belongs to (one capture day of work on a vehicle), FK to work_sessions.id. Written by derive_work_sessions(vehicle) (creates a derived session per capture day of relevant frames and links them; migration 20260622090000), scripts/daily-receipt/build-day.mjs, auto-sort-photos and mcp-connector. Filled on 44.9% of the 30,315 rows with a user_id and 0.05% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.merged_from_vehicle_id IS
'Vehicle the image was moved from (vehicles.id; no FK). Set by relink_testimony(), resort_image() (first move only), reattribute_observation() and demote_observation_to_user() (on the new row), and merge_into_primary() and merge_vehicle_into_primary_by_url() (vehicle merges); unmerge_vehicle() moves rows back by it and clears it. attribute_testimony() leaves it NULL (no source vehicle). Filled on 8.6% of the 30,315 rows with a user_id and about 0.006% of the table (ANALYZE statistics, 2026-10-01). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.superseded_by IS
'Row that replaced this one, FK to vehicle_images.id. Set with is_superseded and superseded_at by reattribute_observation() and demote_observation_to_user(), which copy the image to a new row and hide the original. 680 rows with a user_id (2026-10-06); the other 170 superseded rows were hidden without a replacement row (the 2026-06 and 2026-07 detach repairs, written outside the repo, and import-pcarmarket-listing re-imports). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.superseded_at IS
'When the row was superseded (hidden but kept). Set with is_superseded by reattribute_observation(), demote_observation_to_user(), import-pcarmarket-listing and repair work outside the repo. 2026-05-31 .. 2026-09-28 on 850 rows with a user_id (2026-10-06); every superseded row carries it. Unit: timestamptz (UTC). Grain: one image. Clock: ingest (supersession time).';

-- ── Corrected existing comments ─────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_images."position" IS
'Order of the image within its vehicle as written at insert, not a maintained gallery order. extract-bat-core writes the index of the image in the gallery it is reading (since 2026-01-10), so images added on a later read start mid-list; backfill-images and other listing extractors write their list index; backfill_vehicle_image_positions(), fix_vehicle_images_for_vehicle() and repair_bat_vehicle_gallery_images() renumber a vehicle from 0. Values are distinct per vehicle but often do not start at 0 (observed vehicle minimums include 1, 48, 66, 104 and 135). The per-listing BaT gallery index is exif_data -> listing_positions, keyed by canonical listing URL. display_order holds the same insert-time index. Default 0. Unit: ordinal. Grain: one image. Clock: n/a (as of the last write).';
COMMENT ON COLUMN public.vehicle_images.source IS
'Where this image came from, a free-text slug set at insert (no CHECK; 47 distinct values in ANALYZE statistics, 2026-10-01). Listing imports: bat_import (90.5% of rows), external_import (5.9%), mecum, gooding, bat, facebook_marketplace, classiccars, organization_import, craigslist, jamesedition, snapshot-image-extract, broad_arrow, hagerty and others. Uploads (rows with a user_id): iphoto (Apple Photos sync), user_upload (web upload), capture_relay_ios (iOS capture app), photo_auto_sync, rescrape, drop-folder, ssd_blast, library_recovery, image_intake and others. classify_image_origin(source, image_url) maps known values to owner or listing; trigger trg_enforce_image_origin_consistency uses that to refuse owner photos on a vehicle that has only listing photos. Default: user_upload. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.file_hash IS
'SHA-256 hash for exact duplicate detection, as hex. On uploaded photos it is the hash of the file bytes (the iOS capture app, intake scripts, ingest_image_identity_first(), which also reuses an existing row with the same hash and source). On BaT link rows extract-bat-core hashes the downloaded bytes after text decoding, which is not the file hash; it is comparable only with other BaT link rows. Trigger trg_flag_duplicate_image marks a new row duplicate when the same user already has the hash; unique per vehicle among non-superseded rows (idx_unique_vehicle_file_hash). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.angle IS
'Camera angle label. Values stored (2026-10-06): detail_shot, exterior_three_quarter, interior_dashboard, exterior_side, undercarriage, engine_bay, exterior_front, exterior_rear and others where angle_source is ai_appraiser; front_3quarter_driver, passenger_side, rear_center and similar where angle_source is tier_1_analysis. Written by extract_ai_analysis_to_fields() from ai_scan_metadata.appraiser (angle, else primary_label) and by the deleted analyze-image and analyze-image-tier1 functions; no current edge function writes it, and yono-classify (owner in pipeline_registry) never writes this table. 8,873 of the 30,315 rows with a user_id (29.3%) and 0.14% of the table (ANALYZE statistics). Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.angle_source IS
'How angle was determined. Only two values are stored (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06): ai_appraiser (extract_ai_analysis_to_fields() copied ai_scan_metadata.appraiser.angle; 8,790 rows with a user_id) and tier_1_analysis (the analyze-image-tier1 function, deleted 2026-02-10; 83 rows). Code also defines ai_appraiser_label (from the appraiser primary_label) and backfill_image_angles_v1 (the deleted backfill-image-angles function). Set with angle. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.angle_confidence IS
'Confidence 0-1 of angle. NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06): yono-classify never writes this table, and the angle writers leave it NULL. get_inventory_angle_coverage_metrics() reads it after ai_detected_angle_confidence. Unit: ratio 0-1. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.analysis_history IS
'AI analysis run history as a JSON object (default {}), not an array. Keys: run_<epoch ms> per run with function, tokens and cost (written by the analyze-image edge function, deleted 2026-03-07), and runs and enrichments arrays from writers not established in the repo. Non-empty on 4,099 of the 30,315 rows with a user_id (2026-10-06); no current code writes it. Append-only by convention: never overwrite. Unit: none. Grain: one image. Clock: derived (each entry carries its run time).';
COMMENT ON COLUMN public.vehicle_images.ai_processing_status IS
'AI analysis pipeline status. CHECK (NOT VALID) allows pending, processing, completed, failed, skipped and analyzed. pending (the default; 64.7% of the table, ANALYZE statistics 2026-10-01): not yet processed; an insert with pending fires trigger_photo_pipeline_on_image_insert. processing: currently being analyzed, do not pick up. completed: analysis done. failed: error, may retry (reset_stuck_photo_pipeline_images() requeues until ai_retry_count reaches 3). skipped (17.2%): no analysis will run; extract-bat-core inserts BaT links as skipped since 2026-09-27, and the iOS app marks metadata-only rows skipped. analyzed: written by scripts/daily-receipt/analyze-capture-photos.mjs. Owned by: photo-pipeline-orchestrator, process-all-images-cron, yono-batch-process. Do NOT set to processing without also setting ai_processing_started_at.';
COMMENT ON COLUMN public.vehicle_images.ai_suggestions IS
'JSONB of AI-suggested metadata (angle, vehicle, condition) as raw AI output before human review; do not overwrite. Only scripts/process-personal-library-images.js writes it (personal photo library, 2025-11); photo-pipeline-orchestrator, owner in pipeline_registry, does not. {} (the default) on every row with a user_id and every row of the 2026-10-06 block sample. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.image_medium IS
'Image medium type, CHECK vehicle_images_image_medium_check (NOT VALID): photograph (real camera), render (3D/CGI), drawing (sketch/illustration), screenshot (screen capture), camera, received, web, other. Default: photograph (99.95% of the table, ANALYZE statistics 2026-10-01); camera, received, web and other are in use on import rows (writers not established). photo-pipeline-orchestrator (Gemini classifier) is the authority for this field; yono-analyze does not write it. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.device_fingerprint IS
'Capture device key Make-Model-Lens-Software (each part read from exif_data, Unknown when absent), not a hash. Set at insert by trigger trg_mark_exif_extraction (generate_device_fingerprint(exif_data)) when NULL and exif_data names a device; trigger trg_auto_attribute_device files the same key into device_attributions with a ghost user per device. 16,645 of the 30,315 rows with a user_id carry it, all in that dash-joined form (2026-10-06). Used to attribute photos to a device for ownership tracking. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.vehicle_vin IS
'VIN read from this image. NULL on every row (ANALYZE statistics 2026-10-01; the 30,315 rows with a user_id, 2026-10-06), so NULL means not read, not that no VIN is visible. Only scripts/nuke-photo-sync.py sets it (from a detected VIN); photo-pipeline-orchestrator, owner in pipeline_registry, does not write it. Web pages read it. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.vehicle_confidence IS
'Confidence 0-1 that the image shows its linked vehicle. NULL on every row (ANALYZE statistics 2026-10-01; rows with a user_id 2026-10-06). The 2026-06-14 version of attribute_testimony() wrote it; the live version records confidence in reattribution_audit.reason instead. identify-vehicle-from-image and photo-pipeline-orchestrator do not write it. Unit: ratio 0-1. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.stale IS
'True when the image needs another deep-analysis pass. Set and cleared by scripts/deep-image-analysis-byok.mjs (stale = the verdict is not saturated, written with last_rerun_at) and scripts/daily-receipt/analyze-capture-photos.mjs (stale = the claim is incomplete); photo-pipeline-orchestrator never touches it. True on 7,912 of the 30,315 rows with a user_id and 0.02% of the table (ANALYZE statistics, 2026-10-01). Default false. Unit: boolean. Grain: one image. Clock: derived (as of last_rerun_at).';
COMMENT ON COLUMN public.vehicle_images.zone_source IS
'How vehicle_zone was determined. On rows with a user_id (2026-10-06): yono_local 6,515, backfill_from_appraiser 1,700, yono-contextual 1,445, cluster_propagation 413 (writers of these four are not established in the repo; yono-contextual matches yono/contextual_training). On the table also zone_classifier_v1 (the YONO ZoneClassifierHead, 72.8% val_acc; yono/modal_batch.py and scripts/yono-classify-vehicle.mjs), the most common value (ANALYZE statistics 2026-10-01). The YONO code also defines photo_type_heuristic; manual is not stored. Unit: none. Grain: one image. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_images.fabrication_stage IS
'Build or fabrication stage the image shows, free text with no CHECK. yono-analyze writes a 10-stage taxonomy (raw, disassembled, stripped, fabricated, primed, blocked, basecoated, clearcoated, assembled, complete); scripts/deep-image-analysis.mjs adds media_blasted and welded; scripts/vision-form-fill-ingest.mjs and the daily-receipt scripts write free phase labels. Most stored values are outside the taxonomy: on the 30,315 rows with a user_id (2026-10-06) the top values are electrical 553, disassembly 509, bodywork 452, teardown 391, mechanical 373, finishing 341, assembly 314. Owned by yono-analyze (pipeline_registry). Unit: none. Grain: one image. Clock: derived (as of the writing pass).';

-- A column added between this PR and its deploy must not block the deploy: report, never raise.
DO $$
DECLARE
  missing text;
BEGIN
  SELECT string_agg(a.attname, ', ' ORDER BY a.attnum) INTO missing
  FROM pg_attribute a
  WHERE a.attrelid = 'public.vehicle_images'::regclass
    AND a.attnum > 0
    AND NOT a.attisdropped
    AND col_description(a.attrelid, a.attnum) IS NULL;
  IF missing IS NULL THEN
    RAISE NOTICE 'vehicle_images: every column has a comment';
  ELSE
    RAISE NOTICE 'vehicle_images columns still without a comment: %', missing;
  END IF;
END
$$;

COMMIT;
