-- Describe vehicle_observations: the 33 columns with no COMMENT ON COLUMN (29 of 62 described before, catalog count on
-- prod, 2026-10-07), five corrected column comments and a corrected table comment. Comments only.
-- Describe stage of the repair loop (docs/ledger/theory/data-machine-cases.md section 12; data-machine.md
-- "the database describes itself"). Second row of v_residual: about 11.2M rows, the fact log of data-machine.md.
--
-- METHOD (read 2026-10-07 UTC):
--   Columns, types, defaults, constraints, indexes, policies, grants and existing comments from pg_attribute,
--   pg_constraint, pg_indexes, pg_policy, information_schema and pg_description. Writers from code at origin/main
--   10fba9c35 (supabase/functions, supabase/migrations, database/migrations, scripts, nuke_frontend/src, mcp-servers,
--   apps), git history for deleted writers, the 12 triggers on vehicle_observations, the body of every live public SQL
--   function that names the table (65), pg_cron (observation-discovery, weekly-analyze-vehicle-observations and
--   drain-ars-recompute-queue are paused), prod migration history (supabase_migrations.schema_migrations, which ends
--   2026-07-27) and pipeline_registry (8 rows, owners ingest-observation and discover-from-observations).
--   "Filled" means non-NULL and, for text, non-blank; json and arrays count non-empty.
-- LIMITS:
--   One block sample, TABLESAMPLE SYSTEM (0.2) REPEATABLE (20261006): 21,911 of about 11.18M rows (pg_class.reltuples),
--   ingested 2026-01-24 .. 2026-10-06, 856 of them in the last 30 days. Cross-checked against ANALYZE statistics
--   (pg_stats, 30,000-row sample; its newest ingested_at is 2026-07-18 because the weekly ANALYZE job is paused).
--   Block sampling clusters rows of similar age, so small percentages are rough.
--   Exact counts through partial indexes: superseded_by (1,296), merged_from_vehicle_id (4,072), submitted_by_user_id
--   (2,384), anchor_frame_id (5). The newest rows were read through the ingested_at index, one or two UTC days at a
--   time: 215,357 rows ingested 2026-09-30 .. 2026-10-06. No full-table scan (7.8 GB heap; the read API stops a
--   statement at 10 s). "Empty everywhere measured" means empty in the sample, in ANALYZE statistics and in those
--   7 days.
--   Writer attribution is from code, from row stamps (source, extraction_method, extracted_by, extraction_metadata
--   keys) and from prod migration history. Writers outside the repo are named by their stamps only.
--   Quoted values are categorical codes, method stamps and system messages only: no names, handles, contacts, URLs,
--   ids or amounts.
-- CHANGED EXISTING COMMENTS:
--   source_id: said always required; it is nullable, NULL on 0.09% of the sample, and allowed whenever
--   submitted_by_user_id is set.
--   is_superseded: said ingest-observation sets it when deduplicating; ingest-observation has never set it.
--   agent_tier: its value list matched none of the stored values except system (stored: system, caller-byok, L4).
--   extraction_method: its value list omitted the stamps on most filled rows.
--   raw_source_ref: said URL or listing_page_snapshots id; 391 of the 445 sampled values are BaT live post references.
--   Table comment: called the table immutable and the path of every vehicle data point; rows are updated in place and
--   most vehicle data is written to other tables.

BEGIN;
SET LOCAL statement_timeout = '60s';
SET LOCAL lock_timeout = '5s';

COMMENT ON TABLE public.vehicle_observations IS
'The observation log (data-machine.md: the fact log): one row per sourced claim about one subject, usually a vehicle, from one source at one moment (grain: one observation). Event time = observed_at, whose basis differs by writer (see that column); ingest time = ingested_at. About 11.2M rows (2026-10-07). By volume (0.2% block sample, 2026-10-07): photo_pipeline media rows 82.7%, of which 93% record a classifier failure rather than a reading of the photo (see content_text); BaT comments and bids 6.9% (copies of auction_comments made 2026-01-24 .. 2026-02-10, and the BaT live frames since 2026-10-04); BaT listings and results 4.2%; then other auction listings, description extractions, OCR, condition verdicts and owner rows. Since 2026-10-04 most new rows are BaT live frames (ingest_bat_live_events()). Canonical writer: ingest-observation (pipeline_registry); many writers insert directly (_shared/observationWriter.ts, SQL functions, scripts). Append-only in principle, but rows are updated in place: merges repoint vehicle_id, supersession sets is_superseded, superseded_by and superseded_at, discover-from-observations sets is_processed, confirm_photo_intent() adds keys to structured_data, and merge_into_primary() can delete colliding rows into merge_deleted_rows (none so far). Most vehicle data does not pass through here: vehicles, vehicle_images and auction_comments are written directly. vehicle_id has no foreign key.';

-- ── Identity and subject ────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.id IS
'Surrogate key of the observation. Unit: none (uuid). Source: gen_random_uuid() default; unmerge_vehicle() re-inserts rows archived in merge_deleted_rows with their original id. The successor row that reattribute_observation(), demote_observation_to_user() or reassign_observation_subject() creates gets a new id, and the original keeps its own. Referenced by foreign keys from superseded_by and source_observation_id (this table), build_posts.observation_id, observation_witnesses.observation_id (ON DELETE CASCADE) and vehicle_field_consensus.source_observation_id (2026-10-07). Held without a foreign key in, for example, reattribution_audit, receipts.submitted_observation_id, payment_events.source_observation_id, technician_work_evidence and the uuid arrays of vehicle_field_consensus, projection_event and derivation_queue, and as text in raw_source_ref (vehicle_observations:<id>). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.vehicle_id IS
'Vehicle the observation is about, a vehicles.id with NO foreign key on prod (the creating file database/migrations/20260124_vehicle_observation_system.sql declared one). 234 of the 21,904 sampled rows with a value (1.1%; 108 of 10,664 distinct ids) point at no vehicles row, all ingested 2026-01-24 .. 2026-03-30. NULL on 7 of 21,911 sampled rows (ANALYZE statistics 0.007%) and on 582 of the 215,357 rows ingested 2026-09-30 .. 2026-10-06: unresolved intake (ingest-observation found no match for the caller vehicle_hints, as on the mail-alert listings), non-vehicle subjects (subject_type user or organization; see subject_id) and rows demote_observation_to_user() moved to the user pool. Set at insert by every writer; ingest-observation takes it from the caller or resolves it by VIN, listing URL or year and make (see vehicle_match_confidence). attribute_testimony() fills a NULL; merge_into_primary(), merge_vehicle_into_primary_by_url() and relink_testimony() repoint it in place and record the old id in merged_from_vehicle_id; unmerge_vehicle() moves rows back. Triggers trg_vehicle_observations_count and trg_update_live_metrics queue per-vehicle recounts on insert and change, and the read policy vo_authenticated_read joins vehicles through it. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.vehicle_match_confidence IS
'How sure the writer was that vehicle_id is the right vehicle, 0 .. 1. Source: ingest-observation writes 1.0 when the caller passes vehicle_id, else 0.99 (VIN match), 0.95 (listing URL match), 0.90 (normalized event URL match) or 0.60 (year and make match), and NULL when it resolves none; _shared/observationWriter.ts, migrate-to-observations, the backfill scripts and ingest_cached_image_property_batch() write 1.0; ingest_bat_live_events() writes 0.95. Filled on 98.7% of the 2026-10-07 sample: 1.00 on 96.9%, 0.95 on 1.8% (the BaT live frames since 2026-10-04); NULL on description-extraction, shop condition, sighting and forum rows whose writers omit it. A merge leaves it unchanged when it moves the row, and the successor rows of reattribute_observation(), demote_observation_to_user() and reassign_observation_subject() leave it NULL. Unit: probability, numeric(3,2). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.vehicle_match_signals IS
'What resolved vehicle_id, a JSON object. Keys by writer: ingest-observation, only when it resolved the vehicle from vehicle_hints: vin_match and normalized_vin, normalized_url_match and canonical_id, exact_url_match, normalized_event_url_match, fuzzy_match with year and make, or multiple_candidates with count and the caller hints (left unresolved); ingest_bat_live_events(): source_url_match, native_post_id and binding (bat_auctions_page). NULL when the caller passed vehicle_id. Filled on 1.8% of the 2026-10-07 sample, all BaT live frames; since that writer started on 2026-10-04 it fills most new rows (66,141 of the 72,697 rows ingested on 2026-10-06 UTC). ANALYZE statistics (to 2026-07-18) saw it on 2 of 30,000 rows. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.merged_from_vehicle_id IS
'The vehicle this observation belonged to before a merge or reattribution moved it, a vehicles.id with no foreign key. Set by merge_into_primary(), merge_vehicle_into_primary_by_url() and relink_testimony() when they repoint vehicle_id in place, and on successor rows by reattribute_observation(), demote_observation_to_user() and reassign_observation_subject(); unmerge_vehicle() moves rows back and clears it. 4,072 rows (index read, 2026-10-07) from 17 distinct former vehicles, now on 6 vehicles or in the user pool, ingested 2026-01-24 .. 2026-10-06; 1 of the 21,911 sampled rows. Unit: none. Grain: one observation. Clock: n/a.';

-- ── Source, observer and submitter ──────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.source_id IS
'FK to observation_sources.id (192 sources, 2026-10-07): the source that produced this observation; its base_trust_score seeds confidence_score in ingest-observation. Nullable. Trigger trg_citation_required_vehicle_observations (citation_required_write_check(); no applied migration in the repo installs it, its body is in database/migrations/PROPOSED_institution_minimum_substrate.sql) rejects an insert, or a change of source_id or submitted_by_user_id, that leaves both NULL, so an account-submitted row may have no source. NULL on 20 of 21,911 sampled rows (0.09%; ANALYZE statistics 0.08%): forum build-thread summaries written 2026-01-29 .. 2026-02-11 by scripts/batch-structure-threads-*.js; and on 11 of the 2,384 rows with submitted_by_user_id. ANALYZE statistics: photo_pipeline 83.9%, bat 9.5%, ai-description-extraction 1.8%, mecum 1.3%, barrett-jackson 0.8%, cars-and-bids 0.6%. The same platform can appear under two slugs (cars-and-bids and cars_and_bids, broad-arrow and broad_arrow). Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.source_url IS
'URL of what was observed, as the writer passed it; no normalization or CHECK. By writer: on photo_pipeline media rows (82.7% of the 2026-10-07 sample) the URL of the analyzed image (vehicle_images.image_url, mostly auction image CDNs and Nuke storage), not a page; on listing, sale_result and BaT live rows the listing page; on forum rows the thread. NULL on 7.8% of the sample: the auction_comments copies of migrate-to-observations (2026-01-24 .. 2026-02-10), description extractions, shop condition verdicts, cached property projections and OCR rows. An input of the ingest-observation content_hash; photo-pipeline-orchestrator also matches on it to skip an image it already analyzed. Unit: none (URL text). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.observer_id IS
'Who made the observation, as a foreign key to external_identities.id: the person or account on the source platform, such as a comment author (creating file and docs/library/reference/encyclopedia/02-observation-model.md). UNUSED: no writer sets it; reattribute_observation(), demote_observation_to_user() and reassign_observation_subject() copy it to the successor row. Empty everywhere measured (2026-10-07). Comment and bid authors sit in structured_data.author_username as text instead. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.observer_raw IS
'Who made the observation, before identity resolution: a JSON object from the writer. Keys by writer: add_photo_comment() owner_user_id and authored; record_interaction(), set_vehicle_before_image() and set_vehicle_build_image() user_id; ingest-observation passes the caller object through (the 2026-09 and 2026-10 manual and agent provenance rows carry keys such as publisher, carrier, speaker_id, speaker_role, observer_identity and capture_method); successor copies keep it. Rare: none in the 2026-10-07 sample, 1 of 30,000 rows in ANALYZE statistics, 272 of the 215,357 rows ingested 2026-09-30 .. 2026-10-06 (caption, catalogue and saved-card rows). An input of the ingest-observation content_hash. Holds account ids and speaker identities, so it can identify a person. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.submitted_by_user_id IS
'Signed-in account that submitted the observation, foreign key to auth.users.id. Trigger trg_citation_required_vehicle_observations accepts it in place of source_id: an insert or source change needs one of the two. Writers: record_interaction(), set_vehicle_before_image() and set_vehicle_build_image() (auth.uid()), the K5 wiring ingest scripts and SQL files (scripts/ingest_k5_*.py, database/migrations/20260522_k5_*.sql; 2026-05-17 .. 2026-05-23), a vision-gate audit writer not in this repo (extraction_method vision-gate-l4-*, 2026-05-05 .. 2026-09-26) and manual uploads; successor copies keep it. ingest-observation does not set it. 2,384 rows from one account (index read, 2026-10-07; ingested 2026-04-29 .. 2026-09-26), 11 of them with no source_id; 6 of the 21,911 sampled rows. project_observation_image_witness() copies it to observation_witnesses.added_by_user_id, and api-v1-events lets that account supersede its own rows. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.raw_source_ref IS
'Reference to the raw source the claim was read from, as text: a URL, a typed row reference or a hash; no foreign key, so resolve by prefix. Shapes in the 2026-10-07 sample (445 filled rows, 2.0%): bat:public-live:post:<post id> (391, ingest_bat_live_events()), vehicle_observations:<id> (20, the parent observation of a cached property projection, ingest_cached_image_property_batch()), listing and image URLs (BaT, Mecum), 64-character hashes and pixel_assay:<hash>:<hash> references. The protected archived-sale path of ingest-observation writes listing_page_snapshots:<id>. Written by ingest-observation from the caller and by the SQL writers named; successor copies drop it. Unit: none. Grain: one observation. Clock: n/a.';

-- ── Content ─────────────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.content_text IS
'Main text of the observation as the writer passed it. By writer: on photo_pipeline media rows the classifier one-line description of the image, or its failure text: 16,929 of the 18,122 sampled photo_pipeline media rows (93.4%; 77.3% of all sampled rows) hold Classification failed: ... (2026-02-16 .. 2026-04-06) or Unclassified (classifier unavailable ...) (2026-06-10 .. 2026-10-02) instead of a reading; on comment and bid rows the public comment text, a bid placed line on bids (the migrate-to-observations copies and the BaT live frames; 6,166 of the 17,992 live comment frames of 2026-10-06 keep HTML markup); on html_description_capture rows the whole listing description (689 .. 4,753 characters in the sample); on backfill-from-vehicles and backfill-sale-results rows a year | make | model | price | title line; on forum rows a Build thread: <title> line; on description-extraction, condition-verdict and OCR rows a generated sentence (on OCR rows a caption of the photo). NULL or blank on 5.3% of the 2026-10-07 sample: vehicle_events_migration and html_match listing and result rows, BaT live listing frames, cached property projections and saved media. Up to 4,793 characters in the sample. An input of the ingest-observation content_hash and of its substantial_content confidence factor (over 100 characters). Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.content_hash IS
'Deduplication hash of the observation content, usually 64 hex characters (SHA-256). Part of UNIQUE unique_observation (source_id, source_identifier, kind, content_hash), which never matches a NULL. By writer: ingest-observation hashes a JSON of source slug, kind, vehicle_id, source_url, source_identifier, observed_at, text, structured_data and observer_raw (vehicle_id, observed_at and observer_raw joined on 2026-05-24; descriptor, property and source-comment keys on 2026-09-30 .. 2026-10-02) and answers an existing hash as a duplicate; _shared/observationWriter.ts hashes source, kind, identifier, text and fields, and migrate-to-observations the same without fields; the BaT live frames carry the producer hash; add_photo_comment(), record_interaction(), set_vehicle_before_image() and set_vehicle_build_image() write a 32-character md5; demote_observation_to_user() derives a new SHA-256 from the old hash and the vehicle it left. Because observed_at is an input, the same claim re-read at a new time gets a new hash. NULL on 6.3% of the 2026-10-07 sample: the vehicle_events_migration, backfill-from-vehicles and backfill-sale-results rows (2026-03-24), forum rows and shop condition verdicts, which the unique key therefore does not deduplicate. Unit: none (hex text). Grain: one observation. Clock: n/a.';

-- ── Confidence ──────────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.confidence_score IS
'Numeric confidence in the observation, 0 .. 1, from which the confidence enum is derived. ingest-observation computes observation_sources.base_trust_score plus confidence_factors (vehicle_match 0.10, has_source_url 0.05, substantial_content 0.05, owner_confirmed 0.30), capped at 1.0, and since 2026-09-30 caps it at 0.6 when the caller sets agent_inferred; confidence is verified at 0.95 or more, high at 0.85 or more, low under 0.4, else medium. Other writers store fixed values: ingest_bat_live_events() 0.90, migrate-to-observations 0.85 or 0.90, backfill-from-vehicles 0.85, add_photo_comment(), set_vehicle_before_image() and set_vehicle_build_image() 0.95, record_interaction() 0.6, ingest_cached_image_property_batch() the source trust plus 0.1, capped at 0.6. Filled on 96.7% of the 2026-10-07 sample; ANALYZE statistics: 0.85 on 63.4%, 0.90 on 31.1%. The photo_pipeline classifier-failure rows carry 0.85 or 0.90 (confidence high) because they predate the cap. NULL on vehicle_events_migration listings, forum, saved-media and sighting rows; successor copies leave it NULL. It scores the writer and source, not the truth of the claim. Unit: probability, numeric(3,2). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.confidence_factors IS
'What contributed to confidence_score, a JSON object of named increments; default {}. Keys from ingest-observation: vehicle_match (0.1, when the vehicle match confidence is 0.95 or more), has_source_url (0.05), substantial_content (0.05, content_text over 100 characters), owner_confirmed (0.30, structured_data.owner_confirmed true) and agent_inferred_cap (the negative step that caps an agent-inferred claim at 0.6, since 2026-09-30); ingest_cached_image_property_batch() writes vehicle_match 0.1 and agent_inferred_cap. Non-empty on 84.0% of the 2026-10-07 sample (the ingest-observation and cached-projection rows); {} on rows from writers that compute no factors (BaT live frames, migrated comments, backfills, owner functions). Unit: none (JSON of numbers). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.observed_at_confidence IS
'Confidence in observed_at, 0 .. 1, by name. No writer sets it: rows ingested from 2026-05-03 on carry the default 1.00 and rows ingested up to 2026-04-27 are NULL (2026-10-07 sample: 1.00 on 33.8%, NULL on 66.2%; ANALYZE statistics: 1.00 on 26.1%). The column and its default were added between those dates by a change in neither the repo nor prod migration history. A constant, so it says nothing about the clock. CHECK vehicle_observations_observed_at_confidence_range (0 .. 1) is NOT VALID. The web app reads a different key, structured_data.observed_at_confidence (low, medium, high). Unit: probability, numeric(3,2). Grain: one observation. Clock: n/a.';

-- ── Extraction and processing ───────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.extractor_id IS
'Which extractor produced the observation, meant as an observation_extractors.id (8 rows) by the creating file database/migrations/20260124_vehicle_observation_system.sql; no foreign key. UNUSED: ingest-observation and ingest-observation-batch pass a caller value through, but no caller sends one (extract-bat-core notes that a producer label is not this registry id), and the protected archived-sale path requires it NULL. Empty everywhere measured (2026-10-07). extraction_method and extracted_by carry the producer instead. Unit: none (uuid). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.extraction_metadata IS
'Writer context for the extraction, a JSON object; NULL when the writer sends none. Keys by writer: migrate-to-observations migrated_from (auction_comments), migration_batch and original_id (the auction_comments id as text, on 1,245 of the 1,508 sampled BaT comment and bid rows, ingested 2026-01-24 .. 2026-02-10); ingest_bat_live_events() producer (extract-bat-core), schema (bat_public_live_v1) and paid_model_calls; photo-pipeline-orchestrator (rows from 2026-10-03) pipeline, pipeline_version, observed_at_semantics (analysis_review_time), capture_at and the classifier receipt; the 2026-10 manual and agent normalization rows (caption, catalogue and mail-alert rows) clock and custody keys such as observed_at_semantics, captured_at, source_available_at and content hashes; the protected archived-sale path of ingest-observation producer_qualified_at, clock_basis and the source episode and snapshot context; _shared/observationWriter.ts raw (the caller payload). Filled on 7.5% of the 2026-10-07 sample and on 142,591 of the 215,357 rows ingested 2026-09-30 .. 2026-10-06, mostly BaT live frames. Successor copies drop it. Unit: none. Grain: one observation. Clock: n/a; time keys inside are writer clocks.';
COMMENT ON COLUMN public.vehicle_observations.extraction_method IS
'How the observation was extracted: a free-text method stamp, no CHECK. Filled on 10.7% of the 2026-10-07 sample, 17 distinct values: vehicle_events_migration (scripts/migrate-events-to-observations.sh, deleted; 2026-03-24), bat_public_live_v1 (ingest_bat_live_events(), since 2026-10-04), backfill-from-vehicles and backfill-sale-results (scripts/backfill-*.sh, 2026-03-24), html_match (extract-bat-core through _shared/observationWriter.ts), llm_extraction and description_condition_v1 (description extraction, 2026-03-21 .. 2026-04-01), byok_claude_print_read_tool (shop condition verdicts), html_description_capture (extract-bat-core), cached_byok_property_projection_v1 (ingest_cached_image_property_batch()), and smaller stamps. Recent writers add image_analysis (photo-pipeline-orchestrator, rows from 2026-10-03), gatsby_json_parse (extract-gooding), html_parse, dom_parse, retained_listing_property_projection_v1, mail-alerts-v2 and mail-alerts-v3, and manual or agent review stamps. NULL on every photo_pipeline media row ingested before 2026-10-03 and on the migrated comments. The earlier documented list (llm_extraction, html_parse, ocr, api_response, manual_input, image_analysis, migration) is a subset of what writers send. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.agent_tier IS
'Tier or route of the producer, free text with no CHECK. Stored values (2026-10-07 sample, 261 filled rows, 1.2%): system (180, the description-extraction rows of scripts/promote-discoveries-to-observations.mjs), caller-byok (76, shop condition verdicts and cached BYOK property projections) and L4 (5, vision-gate sightings). The earlier documented list (haiku, sonnet, opus, human, system, migration) matches only system. Written by ingest-observation and ingest-observation-batch from the caller, by ingest_cached_image_property_batch() and by _shared/observationWriter.ts; successor copies keep it. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.processing_metadata IS
'Processing log for the observation, a JSON object, by name and by the creating file database/migrations/20260124_vehicle_observation_system.sql. UNUSED: the only code writer, mcp-servers/nuke-context/ingest-thread.mjs (processor and version), inserts with neither source_id nor submitted_by_user_id, which trigger trg_citation_required_vehicle_observations rejects; discover-from-observations sets is_processed but not this. Empty everywhere measured (2026-10-07). Unit: none. Grain: one observation. Clock: n/a.';

-- ── Supersession and lineage ────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.is_superseded IS
'True when a later observation supersedes this one; the row is kept (testimony is superseded, not overwritten). Default false. Writers: supersede_observation() and supersede_observation_relay() (owner-ordered, with superseded_by), reattribute_observation(), demote_observation_to_user() and reassign_observation_subject() (which first copy the row to a successor), api-v1-events (correction_of), scripts/deep-image-analysis-byok.mjs (a newer BYOK verdict), and set_vehicle_before_image() and set_vehicle_build_image(), which retire the previous owner-designated image row without superseded_by. ingest-observation has never set it: it answers a repeated content_hash as a duplicate (pipeline_registry still names it the owner). True on 0.01% in ANALYZE statistics; 1,296 rows carry superseded_by (index read, 2026-10-07), 1,291 of them superseded by a row from the same source. Partial indexes idx_vehicle_observations_property, idx_vo_pending_owner_confirmation and idx_vobs_specs_covering leave superseded rows out. Unit: boolean. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.superseded_by IS
'The observation that replaced this one, foreign key to vehicle_observations.id; set together with is_superseded true. Writers: supersede_observation() (signed-in owner or contributor) and supersede_observation_relay() (service role, naming the owner who ordered it), reattribute_observation(), demote_observation_to_user() and reassign_observation_subject() (which first copy the row to a successor), api-v1-events (correction_of) and scripts/deep-image-analysis-byok.mjs (a newer BYOK verdict). 1,296 rows (index read, 2026-10-07; 1,260 distinct successors): 520 shop condition verdicts superseded by newer BYOK verdicts (successors 2026-05-23 .. 2026-08-02), 177 receipt-scan rows superseded 2026-05-03 .. 2026-05-23 by a writer not established, 531 receipt-scan rows reattributed or moved to the user pool on 2026-09-28, 57 rows superseded on 2026-09-27 (28 of them through supersede_observation_relay(), per reattribution_audit) and 11 others. set_vehicle_before_image() and set_vehicle_build_image() retire rows without setting it. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.superseded_at IS
'When the row was superseded: the database time of the supersession, a recording clock, not when the claim stopped being true. Written with is_superseded by supersede_observation(), supersede_observation_relay(), reattribute_observation(), demote_observation_to_user(), reassign_observation_subject(), api-v1-events, set_vehicle_before_image() and set_vehicle_build_image(). Filled on 599 of the 1,296 rows with superseded_by (index read, 2026-10-07; 2026-04-29 .. 2026-10-06). NULL on the 520 shop condition verdicts superseded by scripts/deep-image-analysis-byok.mjs and the 177 receipt-scan rows superseded in May 2026, whose writers do not set it. Unit: timestamptz. Grain: one observation. Clock: ingest time (of the supersession).';
COMMENT ON COLUMN public.vehicle_observations.lineage_chain IS
'An array of uuids with two incompatible definitions. The creating file database/migrations/20260124_data_lineage_and_org_services.sql makes it the observation_sources ids of the hops the data took (original source, aggregator, archive), written by record_observation_lineage(), which has no caller and cannot run because its table observation_lineage does not exist on prod. The working writers, supersede_observation() and supersede_observation_relay(), instead append the successor observation id, matching docs/library/reference/encyclopedia/02-observation-model.md (the chain of supersession). Filled on 60 of the 1,296 rows with superseded_by, each equal to [superseded_by] (index read, 2026-10-07); empty in the sample, in ANALYZE statistics and in the rows ingested 2026-09-30 .. 2026-10-06. Unit: none (uuid[]). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.original_source_id IS
'The original source of data that reached us through intermediaries, by the creating file database/migrations/20260124_data_lineage_and_org_services.sql: record_observation_lineage() sets it from the hop with role original_source, taking its observation_sources id or, failing that, its organization id (two id spaces; no foreign key). UNUSED: that function has no caller and cannot run (observation_lineage does not exist on prod). Empty everywhere measured (2026-10-07) and on the 1,296 superseded rows. Unit: none (uuid). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.original_source_url IS
'URL at the original source of data that reached us through intermediaries (the url of the original_source hop), by the same file and writer as original_source_id. UNUSED: record_observation_lineage() has no caller and cannot run (observation_lineage does not exist on prod). Empty everywhere measured (2026-10-07). Unit: none (URL text). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.discovered_via_id IS
'Unknown meaning: two documents define it differently. The creating file database/migrations/20260124_data_lineage_and_org_services.sql makes it the observation_sources id of the archive, aggregator or discovery-tool hop that led us to the data (record_observation_lineage()); docs/library/reference/encyclopedia/02-observation-model.md makes it the observation that led to discovering this one. No foreign key. UNUSED: its only writer has no caller and cannot run (observation_lineage does not exist on prod). Empty everywhere measured (2026-10-07). Unit: none (uuid). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.data_freshness_at_discovery IS
'How old the data was when we found it, by the creating file database/migrations/20260124_data_lineage_and_org_services.sql and the encyclopedia (a listing read hours after posting versus a copy found in an archive years later). UNUSED: no writer in the repo or in live SQL. Empty everywhere measured (2026-10-07). ingested_at minus observed_at gives a comparable age where observed_at is a source event time. Unit: interval. Grain: one observation. Clock: derived (ingest time minus source time).';

-- ── VFC write envelope and build ────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.changeset_id IS
'The write envelope this observation belongs to, foreign key to vfc_changesets.id (VFC v0 section 11: a wrapper around 1 .. N actions, the federation unit; 6 rows on 2026-10-07). Added on prod on 2026-05-01 by migration vfc_v0_step2_changesets_table (prod history; not in the repo). UNUSED: no writer in the repo or in live SQL. Empty everywhere measured (2026-10-07). Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.applies_to_build_id IS
'The build variant the observation applies to, foreign key to vfc_builds.id (VFC v0 section 7: composition arc records; a vehicle can have several concurrent build variants; 3 rows on 2026-10-07). Added on prod on 2026-05-01 by migration vfc_v0_step3_builds_table (prod history; not in the repo). UNUSED: no writer in the repo or in live SQL. Empty everywhere measured (2026-10-07). Unit: none. Grain: one observation. Clock: n/a.';

-- ── Citation ────────────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.citation_page_number IS
'Page of the cited document the claim was read from, with citation_document_id or citation_secure_document_id. Source: ingest-observation (citation.page_number); added by database/migrations/20260522_reference_documents_substrate.sql. Empty everywhere measured (2026-10-07). Unit: page number (integer). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.citation_excerpt IS
'The verbatim words the claim was read from. Source: ingest-observation (citation.excerpt); descriptor (condition) claims put the quoted listing words here (see descriptor_id). Added by database/migrations/20260522_reference_documents_substrate.sql. Rare: none in the 2026-10-07 sample or in ANALYZE statistics; 19 of the 215,357 rows ingested 2026-09-30 .. 2026-10-06: 18 saved-card listing rows about a user subject (extraction_method browser_saved_card_dom_v1) and 1 condition claim (claim_from_listing_text), by writers not in this repo. Can quote seller or owner text. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.citation_secure_document_id IS
'The private owner document the claim cites (a title or bill of sale), foreign key to secure_documents.id (NOT VALID). Source: ingest-observation (citation.secure_document_id); added by supabase/migrations/20260709210000_cite_secure_documents.sql. citation_document_id is the shared-library counterpart. Empty everywhere measured (2026-10-07). Unit: none. Grain: one observation. Clock: n/a.';

-- ── Spatial anchor ──────────────────────────────────────────────────────────────────────────────────────────────

COMMENT ON COLUMN public.vehicle_observations.anchor_frame_id IS
'Coordinate frame of the spatial anchor, foreign key to vehicle_coordinate_frames.id (1 frame row on 2026-10-07). With anchor_x_mm, anchor_y_mm, anchor_z_mm and anchor_extent_mm it places the claim at a point on the vehicle body (supabase/migrations/20260702051500_xyz_spatial_anchors.sql, design of 2026-05-24); condition_rating_0_100 rates that volume. Filled on 5 rows (index read, 2026-10-07): one vehicle, shop condition verdicts ingested 2026-07-11 (extraction_method byok_claude_print_read_tool) by a writer not in this repo, each with a condition rating. Unit: none. Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.anchor_y_mm IS
'Y coordinate of the spatial anchor in the anchor_frame_id frame; see anchor_x_mm for the landing rule. Filled on the same 5 rows as anchor_frame_id (2026-07-11): -200 .. 250. The one frame row declares units m and axis convention gltf_Y_up_Z_forward, while the column names say millimetres, so the unit of the stored numbers is not recorded. Unit: millimetres by name (real). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.anchor_z_mm IS
'Z coordinate of the spatial anchor in the anchor_frame_id frame; see anchor_x_mm for the landing rule. Filled on the same 5 rows as anchor_frame_id (2026-07-11): -1,150 .. 2,300. The one frame row declares units m and axis convention gltf_Y_up_Z_forward, while the column names say millimetres, so the unit of the stored numbers is not recorded. Unit: millimetres by name (real). Grain: one observation. Clock: n/a.';
COMMENT ON COLUMN public.vehicle_observations.anchor_extent_mm IS
'Size of the anchored volume around the point that condition_rating_0_100 rates, by name and the spatial-anchor migration; whether it is a radius or a diameter is not stated. Filled on the same 5 rows as anchor_frame_id (2026-07-11): 300 .. 2,200. Unit: millimetres by name (real). Grain: one observation. Clock: n/a.';

-- A column added between this PR and its deploy must not block the deploy: report, never raise.
DO $$
DECLARE
  missing text;
BEGIN
  SELECT string_agg(a.attname, ', ' ORDER BY a.attnum) INTO missing
  FROM pg_attribute a
  WHERE a.attrelid = 'public.vehicle_observations'::regclass
    AND a.attnum > 0
    AND NOT a.attisdropped
    AND col_description(a.attrelid, a.attnum) IS NULL;
  IF missing IS NULL THEN
    RAISE NOTICE 'vehicle_observations: every column has a comment';
  ELSE
    RAISE NOTICE 'vehicle_observations columns still without a comment: %', missing;
  END IF;
END
$$;

COMMIT;
