name: Auto Fix TypeScript Errors

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Setup .npmrc
        run: |
          echo "legacy-peer-deps=true" > .npmrc
          echo "fund=false" >> .npmrc
          echo "audit=false" >> .npmrc

      - name: Install dependencies
        run: |
          npm ci
          echo "${PWD}/node_modules/.bin" >> $GITHUB_PATH

      - name: Download workflow artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            
            const buildLogs = artifacts.data.artifacts.find(artifact => artifact.name === "typescript-errors");
            if (buildLogs) {
              const download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: buildLogs.id,
                archive_format: 'zip'
              });
              
              const fs = require('fs');
              fs.writeFileSync('typescript-errors.zip', Buffer.from(download.data));
              require('child_process').execSync('unzip -o typescript-errors.zip');
            } else {
              console.log('No TypeScript error artifacts found');
            }

      - name: Make scripts executable
        run: chmod +x .github/scripts/auto-fix-typescript.mjs
          
      - name: Apply specialized automatic fixes
        id: auto-fix
        run: |
          # Run our specialized auto-fix script first
          node .github/scripts/auto-fix-typescript.mjs
          
          # Run ESLint with --fix option and our specialized config
          npx eslint --fix --config .github/eslint-autofix.cjs "src/components/VehicleTimeline/**/*.{ts,tsx}" || true
          
          # Run general ESLint fixes on other files
          npx eslint --fix "src/**/*.{ts,tsx}" || true
          
          # Run TypeScript compiler with --noEmit to check if issues are fixed
          npx tsc --noEmit || true
          
          # Check if there are any changes after auto-fixing
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Fixed TypeScript errors automatically" >> $GITHUB_STEP_SUMMARY
            echo "changes_made=true" >> $GITHUB_OUTPUT
          else
            echo "No automatic fixes were possible" >> $GITHUB_STEP_SUMMARY
            echo "changes_made=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.auto-fix.outputs.changes_made == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git add -A
          git commit -m "🤖 Auto-fix TypeScript errors [skip ci]"
          git push
          
          echo "✅ Pushed automatic fixes to ${{ github.event.workflow_run.head_branch }}" >> $GITHUB_STEP_SUMMARY

      - name: Create Pull Request if branch is not main
        if: steps.auto-fix.outputs.changes_made == 'true' && github.event.workflow_run.head_branch != 'main'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Auto-fix TypeScript errors"
          branch: auto-fix-typescript/${{ github.event.workflow_run.head_sha }}
          delete-branch: true
          title: "🤖 Auto-fix TypeScript errors for VehicleTimeline"
          body: |
            This PR was automatically created by the Auto Fix TypeScript Errors workflow.
            
            It contains fixes for TypeScript errors found in the CI workflow run.
            
            ### What was fixed
            - Fixed TypeScript errors related to accessing properties on potentially null objects
            - Added proper null checks for timeline events
            - Fixed type assertions for the multi-source connector framework
            - Ensured proper ID handling for temporary timeline events
            
            These changes maintain the integrity of the vehicle-centric architecture and multi-source connector framework while preserving the confidence scoring and data reliability mechanisms.
