name: Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Minimal global permissions
permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Run TypeScript check
      id: typescript_check
      run: npx tsc --noEmit
      continue-on-error: true
    
    - name: Create .env file for build
      run: |
        cat > .env << EOF
        # Supabase configuration
        VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_SUPABASE_SERVICE_KEY=${{ secrets.VITE_SUPABASE_SERVICE_KEY }}
        
        # Application configuration
        VITE_APP_NAME=Nuke
        VITE_ENV=production
        VITE_ENABLE_DEBUG=false
        EOF
    
    - name: Build
      run: npm run build
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
        CI: true
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_SUPABASE_SERVICE_KEY: ${{ secrets.VITE_SUPABASE_SERVICE_KEY }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: dist/
        retention-days: 3
        if-no-files-found: warn
