name: Docker Build Test
on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Environment information
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Running in Docker container"
          
      - name: Install dependencies
        run: |
          # Install dependencies with clean environment
          npm ci || npm install
          
      - name: Build directly in Docker
        env:
          NODE_ENV: production
          VITE_APP_NAME: "Nuke"
          VITE_APP_DESCRIPTION: "Vehicle Management Platform"
        run: |
          # Run build with verbose logging
          echo "Running build in Docker container"
          npx --no -- tsc && npx --no -- vite build --debug
          
      - name: Check build output
        run: |
          echo "Checking build output"
          ls -la dist/ || echo "No dist directory found"
