name: Test Docker Hub Authentication

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable extra debugging output'
        required: false
        default: 'false'
        type: boolean

jobs:
  test-docker-auth:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check for Docker Hub secrets
        id: check-secrets
        run: |
          if [ -n "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
            echo "Docker Hub username is configured"
            echo "docker_hub_username_configured=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Docker Hub username is missing"
            echo "docker_hub_username_configured=false" >> $GITHUB_OUTPUT
          fi
          
          if [ -n "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
            echo "Docker Hub token is configured"
            echo "docker_hub_token_configured=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ Docker Hub token is missing"
            echo "docker_hub_token_configured=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Display masked credentials (safe)
        if: inputs.debug == true
        run: |
          echo "Username first 2 chars: ${DOCKER_USERNAME:0:2}..."
          echo "Token length: ${#DOCKER_TOKEN} characters"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Test Docker Hub login
        if: steps.check-secrets.outputs.docker_hub_username_configured == 'true' && steps.check-secrets.outputs.docker_hub_token_configured == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Verify successful login
        if: steps.check-secrets.outputs.docker_hub_username_configured == 'true' && steps.check-secrets.outputs.docker_hub_token_configured == 'true'
        run: |
          echo "✅ Successfully authenticated with Docker Hub"
          echo "  Username: ${{ secrets.DOCKER_HUB_USERNAME }}"
          echo "  Docker Hub account: https://hub.docker.com/u/${{ secrets.DOCKER_HUB_USERNAME }}"
          
          # Get auth info (safely)
          AUTH_INFO=$(docker info | grep "Username:" || echo "Not logged in")
          echo "  Auth info: $AUTH_INFO"
      
      - name: Generate authentication report
        run: |
          echo "# Docker Hub Authentication Test Results" > auth_report.md
          echo "" >> auth_report.md
          
          if [ "${{ steps.check-secrets.outputs.docker_hub_username_configured }}" == "true" ]; then
            echo "✅ Docker Hub username is configured" >> auth_report.md
          else
            echo "❌ Docker Hub username is missing" >> auth_report.md
            echo "  - Go to Settings > Secrets > Actions and add DOCKER_HUB_USERNAME" >> auth_report.md
          fi
          
          if [ "${{ steps.check-secrets.outputs.docker_hub_token_configured }}" == "true" ]; then
            echo "✅ Docker Hub token is configured" >> auth_report.md
          else
            echo "❌ Docker Hub token is missing" >> auth_report.md
            echo "  - Go to Settings > Secrets > Actions and add DOCKER_HUB_TOKEN" >> auth_report.md
            echo "  - Create a token at https://hub.docker.com/settings/security" >> auth_report.md
          fi
          
          echo "" >> auth_report.md
          echo "## Next Steps" >> auth_report.md
          
          if [ "${{ steps.check-secrets.outputs.docker_hub_username_configured }}" == "true" ] && [ "${{ steps.check-secrets.outputs.docker_hub_token_configured }}" == "true" ]; then
            echo "- Run the main Docker build workflow" >> auth_report.md
            echo "- Check your Docker Hub account for the pushed image" >> auth_report.md
          else
            echo "- Add the missing secrets mentioned above" >> auth_report.md
            echo "- Run this test workflow again to verify" >> auth_report.md
          fi
      
      - name: Upload authentication report
        uses: actions/upload-artifact@v4
        with:
          name: docker-auth-report
          path: auth_report.md
          retention-days: 1
