name: Docker Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/nuke:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/nuke:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker image
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/nuke:latest nginx -t
          echo "Docker image built and tested successfully"
      
      - name: Update deployment status
        if: success() && github.event_name != 'pull_request'
        run: |
          echo "🚀 Docker image pushed to Docker Hub successfully!"
          echo "Image: ${{ secrets.DOCKER_HUB_USERNAME }}/nuke:latest"
          echo "Image with SHA: ${{ secrets.DOCKER_HUB_USERNAME }}/nuke:${{ github.sha }}"
